<?php
/**
 * Ce fichier permet de paramétrer le générateur.
 *
 * @package openfoncier
 * @version SVN : $Id$
 */
$permissions = array(

    "consultation_modifier_bypass",
    "consultation_supprimer_bypass",
    "consultation_ajouter_bypass",
    "consultation_modifier_lu_bypass",
    "consultation_consulter_bypass",
    "consultation_finaliser_bypass",
    "consultation_definaliser_bypass",
    "rapport_instruction_rediger_bypass",
    "rapport_instruction_supprimer_bypass",
    "rapport_instruction_ajouter_bypass",
    "rapport_instruction_consulter_bypass",
    "rapport_instruction_finaliser_bypass",
    "rapport_instruction_definaliser_bypass",
    "dossier_contrainte_tab_bypass",
    "dossier_contrainte_supprimer_bypass",
    "dossier_contrainte_ajouter_bypass",
    "dossier_contrainte_modifier_bypass",
    "dossier_contrainte_consulter_bypass",
    "blocnote_ajouter_bypass",
    "blocnote_modifier_bypass",
    "blocnote_supprimer_bypass",
    "document_numerise_ajouter_bypass",
    "document_numerise_modifier_bypass",
    "document_numerise_supprimer_bypass",
    "dossier_message_ajouter_bypass",
    "dossier_message_modifier_bypass",
    "dossier_message_supprimer_bypass",
    "dossier_message_modifier_lu_bypass",
    "dossier_instruction_modifier_bypass",
    "dossier_instruction_donnees_techniques_consulter_bypass",
    "dossier_instruction_rapport_instruction_rediger_bypass",
    "dossier_commission_modifier_bypass",
    "dossier_commission_supprimer_bypass",
    "dossier_commission_ajouter_bypass",
    "dossier_commission_modifier_lu_bypass",
    "dossier_instruction_geolocalisation_consulter_bypass",
    "lot_ajouter_bypass",
    "lot_modifier_bypass",
    "lot_supprimer_bypass",
    "lot_transferer_bypass",
    "lot_editer_donnees_bypass",
    "dossier_instruction_mes_encours_modifier_bypass",
    "dossier_instruction_mes_encours_donnees_techniques_consulter_bypass",
    "dossier_instruction_mes_encours_rapport_instruction_rediger_bypass",
    "dossier_instruction_mes_encours_geolocalisation_consulter_bypass",
    "dossier_instruction_tous_encours_modifier_bypass",
    "dossier_instruction_tous_encours_donnees_techniques_consulter_bypass",
    "dossier_instruction_tous_encours_rapport_instruction_rediger_bypass",
    "dossier_instruction_tous_encours_geolocalisation_consulter_bypass",
    "dossier_instruction_mes_clotures_modifier_bypass",
    "dossier_instruction_mes_clotures_donnees_techniques_consulter_bypass",
    "dossier_instruction_mes_clotures_rapport_instruction_rediger_bypass",
    "dossier_instruction_mes_clotures_geolocalisation_consulter_bypass",
    "dossier_instruction_tous_clotures_modifier_bypass",
    "dossier_instruction_tous_clotures_donnees_techniques_consulter_bypass",
    "dossier_instruction_tous_clotures_rapport_instruction_rediger_bypass",
    "dossier_instruction_tous_clotures_geolocalisation_consulter_bypass",
    "instruction_definaliser_bypass",
    "instruction_finaliser_bypass",
    "instruction_ajouter_bypass",
    "instruction_supprimer_bypass",
    "instruction_modifier_bypass",
    "instruction_modification_dates_bypass",
    "instruction_modification_dates_cloture",
    "donnees_techniques_supprimer_bypass",
    "donnees_techniques_modifier_bypass",
    "consultation_suivi_retours_de_consultation",
    "consultation_saisir_date_envoi",
    "consultation_retour_avis_suivi",
    "consultation_retour_avis_service",
    "consultation_modifier_date_reception",
    "dossier_modifier_instructeur",
    "dossier_modifier_division",
    "consultation_tab_di",
    "dossier_instruction_simulation_taxes",
    "dossier_instruction_acceder_attest_date_affi",
    "dossier_instruction_mes_encours_acceder_attest_date_affi",
    "dossier_instruction_mes_clotures_acceder_attest_date_affi",
    "dossier_instruction_tous_encours_acceder_attest_date_affi",
    "dossier_instruction_tous_clotures_acceder_attest_date_affi",
    "dossier_instruction_modifier_date_affichage",
    "dossier_instruction_mes_encours_modifier_date_affichage",
    "dossier_instruction_mes_clotures_modifier_date_affichage",
    "dossier_instruction_tous_encours_modifier_date_affichage",
    "dossier_instruction_tous_clotures_modifier_date_affichage",

);

$files_to_avoid = array(
    "digitalizedDocument.class.php",
    "pdf_lettre_rar.class.php",
    "import_specific.class.php",
    "reqmo.class.php",
    "sitadel.class.php",
    "synchronisationContrainte.class.php",

);

?>
