<?php
//$Id$ 
//gen openMairie le 29/08/2023 16:10

$DEBUG=0;
$serie=15;
$ent = __("application")." -> ".__("cerfa");
$om_validite = true;
if(!isset($premier)) $premier='';
if(!isset($tricolsf)) $tricolsf='';
if(!isset($premiersf)) $premiersf='';
if(!isset($selection)) $selection='';
if(!isset($retourformulaire)) $retourformulaire='';
if (!isset($idxformulaire)) {
    $idxformulaire = '';
}
if (!isset($tricol)) {
    $tricol = '';
}
if (!isset($valide)) {
    $valide = '';
}
// FROM 
$table = DB_PREFIXE."cerfa";
// SELECT 
$champAffiche = array(
    'cerfa.cerfa as "'.__("cerfa").'"',
    'cerfa.libelle as "'.__("libelle").'"',
    'cerfa.code as "'.__("code").'"',
    'to_char(cerfa.om_validite_debut ,\'DD/MM/YYYY\') as "'.__("om_validite_debut").'"',
    'to_char(cerfa.om_validite_fin ,\'DD/MM/YYYY\') as "'.__("om_validite_fin").'"',
    "case cerfa.am_lotiss when 't' then 'Oui' else 'Non' end as \"".__("am_lotiss")."\"",
    "case cerfa.am_autre_div when 't' then 'Oui' else 'Non' end as \"".__("am_autre_div")."\"",
    "case cerfa.am_camping when 't' then 'Oui' else 'Non' end as \"".__("am_camping")."\"",
    "case cerfa.am_caravane when 't' then 'Oui' else 'Non' end as \"".__("am_caravane")."\"",
    "case cerfa.am_carav_duree when 't' then 'Oui' else 'Non' end as \"".__("am_carav_duree")."\"",
    "case cerfa.am_statio when 't' then 'Oui' else 'Non' end as \"".__("am_statio")."\"",
    "case cerfa.am_statio_cont when 't' then 'Oui' else 'Non' end as \"".__("am_statio_cont")."\"",
    "case cerfa.am_affou_exhau when 't' then 'Oui' else 'Non' end as \"".__("am_affou_exhau")."\"",
    "case cerfa.am_affou_exhau_sup when 't' then 'Oui' else 'Non' end as \"".__("am_affou_exhau_sup")."\"",
    "case cerfa.am_affou_prof when 't' then 'Oui' else 'Non' end as \"".__("am_affou_prof")."\"",
    "case cerfa.am_exhau_haut when 't' then 'Oui' else 'Non' end as \"".__("am_exhau_haut")."\"",
    "case cerfa.am_coupe_abat when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_abat")."\"",
    "case cerfa.am_prot_plu when 't' then 'Oui' else 'Non' end as \"".__("am_prot_plu")."\"",
    "case cerfa.am_prot_muni when 't' then 'Oui' else 'Non' end as \"".__("am_prot_muni")."\"",
    "case cerfa.am_mobil_voyage when 't' then 'Oui' else 'Non' end as \"".__("am_mobil_voyage")."\"",
    "case cerfa.am_aire_voyage when 't' then 'Oui' else 'Non' end as \"".__("am_aire_voyage")."\"",
    "case cerfa.am_rememb_afu when 't' then 'Oui' else 'Non' end as \"".__("am_rememb_afu")."\"",
    "case cerfa.am_parc_resid_loi when 't' then 'Oui' else 'Non' end as \"".__("am_parc_resid_loi")."\"",
    "case cerfa.am_sport_moto when 't' then 'Oui' else 'Non' end as \"".__("am_sport_moto")."\"",
    "case cerfa.am_sport_attrac when 't' then 'Oui' else 'Non' end as \"".__("am_sport_attrac")."\"",
    "case cerfa.am_sport_golf when 't' then 'Oui' else 'Non' end as \"".__("am_sport_golf")."\"",
    "case cerfa.am_mob_art when 't' then 'Oui' else 'Non' end as \"".__("am_mob_art")."\"",
    "case cerfa.am_modif_voie_esp when 't' then 'Oui' else 'Non' end as \"".__("am_modif_voie_esp")."\"",
    "case cerfa.am_plant_voie_esp when 't' then 'Oui' else 'Non' end as \"".__("am_plant_voie_esp")."\"",
    "case cerfa.am_chem_ouv_esp when 't' then 'Oui' else 'Non' end as \"".__("am_chem_ouv_esp")."\"",
    "case cerfa.am_agri_peche when 't' then 'Oui' else 'Non' end as \"".__("am_agri_peche")."\"",
    "case cerfa.am_crea_voie when 't' then 'Oui' else 'Non' end as \"".__("am_crea_voie")."\"",
    "case cerfa.am_modif_voie_exist when 't' then 'Oui' else 'Non' end as \"".__("am_modif_voie_exist")."\"",
    "case cerfa.am_crea_esp_sauv when 't' then 'Oui' else 'Non' end as \"".__("am_crea_esp_sauv")."\"",
    "case cerfa.am_crea_esp_class when 't' then 'Oui' else 'Non' end as \"".__("am_crea_esp_class")."\"",
    "case cerfa.am_projet_desc when 't' then 'Oui' else 'Non' end as \"".__("am_projet_desc")."\"",
    "case cerfa.am_terr_surf when 't' then 'Oui' else 'Non' end as \"".__("am_terr_surf")."\"",
    "case cerfa.am_tranche_desc when 't' then 'Oui' else 'Non' end as \"".__("am_tranche_desc")."\"",
    "case cerfa.am_lot_max_nb when 't' then 'Oui' else 'Non' end as \"".__("am_lot_max_nb")."\"",
    "case cerfa.am_lot_max_shon when 't' then 'Oui' else 'Non' end as \"".__("am_lot_max_shon")."\"",
    "case cerfa.am_lot_cstr_cos when 't' then 'Oui' else 'Non' end as \"".__("am_lot_cstr_cos")."\"",
    "case cerfa.am_lot_cstr_plan when 't' then 'Oui' else 'Non' end as \"".__("am_lot_cstr_plan")."\"",
    "case cerfa.am_lot_cstr_vente when 't' then 'Oui' else 'Non' end as \"".__("am_lot_cstr_vente")."\"",
    "case cerfa.am_lot_fin_diff when 't' then 'Oui' else 'Non' end as \"".__("am_lot_fin_diff")."\"",
    "case cerfa.am_lot_consign when 't' then 'Oui' else 'Non' end as \"".__("am_lot_consign")."\"",
    "case cerfa.am_lot_gar_achev when 't' then 'Oui' else 'Non' end as \"".__("am_lot_gar_achev")."\"",
    "case cerfa.am_lot_vente_ant when 't' then 'Oui' else 'Non' end as \"".__("am_lot_vente_ant")."\"",
    "case cerfa.am_empl_nb when 't' then 'Oui' else 'Non' end as \"".__("am_empl_nb")."\"",
    "case cerfa.am_tente_nb when 't' then 'Oui' else 'Non' end as \"".__("am_tente_nb")."\"",
    "case cerfa.am_carav_nb when 't' then 'Oui' else 'Non' end as \"".__("am_carav_nb")."\"",
    "case cerfa.am_mobil_nb when 't' then 'Oui' else 'Non' end as \"".__("am_mobil_nb")."\"",
    "case cerfa.am_pers_nb when 't' then 'Oui' else 'Non' end as \"".__("am_pers_nb")."\"",
    "case cerfa.am_empl_hll_nb when 't' then 'Oui' else 'Non' end as \"".__("am_empl_hll_nb")."\"",
    "case cerfa.am_hll_shon when 't' then 'Oui' else 'Non' end as \"".__("am_hll_shon")."\"",
    "case cerfa.am_periode_exploit when 't' then 'Oui' else 'Non' end as \"".__("am_periode_exploit")."\"",
    "case cerfa.am_exist_agrand when 't' then 'Oui' else 'Non' end as \"".__("am_exist_agrand")."\"",
    "case cerfa.am_exist_date when 't' then 'Oui' else 'Non' end as \"".__("am_exist_date")."\"",
    "case cerfa.am_exist_num when 't' then 'Oui' else 'Non' end as \"".__("am_exist_num")."\"",
    "case cerfa.am_exist_nb_avant when 't' then 'Oui' else 'Non' end as \"".__("am_exist_nb_avant")."\"",
    "case cerfa.am_exist_nb_apres when 't' then 'Oui' else 'Non' end as \"".__("am_exist_nb_apres")."\"",
    "case cerfa.am_coupe_bois when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_bois")."\"",
    "case cerfa.am_coupe_parc when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_parc")."\"",
    "case cerfa.am_coupe_align when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_align")."\"",
    "case cerfa.am_coupe_ess when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_ess")."\"",
    "case cerfa.am_coupe_age when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_age")."\"",
    "case cerfa.am_coupe_dens when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_dens")."\"",
    "case cerfa.am_coupe_qual when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_qual")."\"",
    "case cerfa.am_coupe_trait when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_trait")."\"",
    "case cerfa.am_coupe_autr when 't' then 'Oui' else 'Non' end as \"".__("am_coupe_autr")."\"",
    "case cerfa.co_archi_recours when 't' then 'Oui' else 'Non' end as \"".__("co_archi_recours")."\"",
    "case cerfa.co_cstr_nouv when 't' then 'Oui' else 'Non' end as \"".__("co_cstr_nouv")."\"",
    "case cerfa.co_cstr_exist when 't' then 'Oui' else 'Non' end as \"".__("co_cstr_exist")."\"",
    "case cerfa.co_cloture when 't' then 'Oui' else 'Non' end as \"".__("co_cloture")."\"",
    "case cerfa.co_elec_tension when 't' then 'Oui' else 'Non' end as \"".__("co_elec_tension")."\"",
    "case cerfa.co_div_terr when 't' then 'Oui' else 'Non' end as \"".__("co_div_terr")."\"",
    "case cerfa.co_projet_desc when 't' then 'Oui' else 'Non' end as \"".__("co_projet_desc")."\"",
    "case cerfa.co_anx_pisc when 't' then 'Oui' else 'Non' end as \"".__("co_anx_pisc")."\"",
    "case cerfa.co_anx_gara when 't' then 'Oui' else 'Non' end as \"".__("co_anx_gara")."\"",
    "case cerfa.co_anx_veran when 't' then 'Oui' else 'Non' end as \"".__("co_anx_veran")."\"",
    "case cerfa.co_anx_abri when 't' then 'Oui' else 'Non' end as \"".__("co_anx_abri")."\"",
    "case cerfa.co_anx_autr when 't' then 'Oui' else 'Non' end as \"".__("co_anx_autr")."\"",
    "case cerfa.co_anx_autr_desc when 't' then 'Oui' else 'Non' end as \"".__("co_anx_autr_desc")."\"",
    "case cerfa.co_tot_log_nb when 't' then 'Oui' else 'Non' end as \"".__("co_tot_log_nb")."\"",
    "case cerfa.co_tot_ind_nb when 't' then 'Oui' else 'Non' end as \"".__("co_tot_ind_nb")."\"",
    "case cerfa.co_tot_coll_nb when 't' then 'Oui' else 'Non' end as \"".__("co_tot_coll_nb")."\"",
    "case cerfa.co_mais_piece_nb when 't' then 'Oui' else 'Non' end as \"".__("co_mais_piece_nb")."\"",
    "case cerfa.co_mais_niv_nb when 't' then 'Oui' else 'Non' end as \"".__("co_mais_niv_nb")."\"",
    "case cerfa.co_fin_lls_nb when 't' then 'Oui' else 'Non' end as \"".__("co_fin_lls_nb")."\"",
    "case cerfa.co_fin_aa_nb when 't' then 'Oui' else 'Non' end as \"".__("co_fin_aa_nb")."\"",
    "case cerfa.co_fin_ptz_nb when 't' then 'Oui' else 'Non' end as \"".__("co_fin_ptz_nb")."\"",
    "case cerfa.co_fin_autr_nb when 't' then 'Oui' else 'Non' end as \"".__("co_fin_autr_nb")."\"",
    "case cerfa.co_fin_autr_desc when 't' then 'Oui' else 'Non' end as \"".__("co_fin_autr_desc")."\"",
    "case cerfa.co_mais_contrat_ind when 't' then 'Oui' else 'Non' end as \"".__("co_mais_contrat_ind")."\"",
    "case cerfa.co_uti_pers when 't' then 'Oui' else 'Non' end as \"".__("co_uti_pers")."\"",
    "case cerfa.co_uti_vente when 't' then 'Oui' else 'Non' end as \"".__("co_uti_vente")."\"",
    "case cerfa.co_uti_loc when 't' then 'Oui' else 'Non' end as \"".__("co_uti_loc")."\"",
    "case cerfa.co_uti_princ when 't' then 'Oui' else 'Non' end as \"".__("co_uti_princ")."\"",
    "case cerfa.co_uti_secon when 't' then 'Oui' else 'Non' end as \"".__("co_uti_secon")."\"",
    "case cerfa.co_resid_agees when 't' then 'Oui' else 'Non' end as \"".__("co_resid_agees")."\"",
    "case cerfa.co_resid_etud when 't' then 'Oui' else 'Non' end as \"".__("co_resid_etud")."\"",
    "case cerfa.co_resid_tourism when 't' then 'Oui' else 'Non' end as \"".__("co_resid_tourism")."\"",
    "case cerfa.co_resid_hot_soc when 't' then 'Oui' else 'Non' end as \"".__("co_resid_hot_soc")."\"",
    "case cerfa.co_resid_soc when 't' then 'Oui' else 'Non' end as \"".__("co_resid_soc")."\"",
    "case cerfa.co_resid_hand when 't' then 'Oui' else 'Non' end as \"".__("co_resid_hand")."\"",
    "case cerfa.co_resid_autr when 't' then 'Oui' else 'Non' end as \"".__("co_resid_autr")."\"",
    "case cerfa.co_resid_autr_desc when 't' then 'Oui' else 'Non' end as \"".__("co_resid_autr_desc")."\"",
    "case cerfa.co_foyer_chamb_nb when 't' then 'Oui' else 'Non' end as \"".__("co_foyer_chamb_nb")."\"",
    "case cerfa.co_log_1p_nb when 't' then 'Oui' else 'Non' end as \"".__("co_log_1p_nb")."\"",
    "case cerfa.co_log_2p_nb when 't' then 'Oui' else 'Non' end as \"".__("co_log_2p_nb")."\"",
    "case cerfa.co_log_3p_nb when 't' then 'Oui' else 'Non' end as \"".__("co_log_3p_nb")."\"",
    "case cerfa.co_log_4p_nb when 't' then 'Oui' else 'Non' end as \"".__("co_log_4p_nb")."\"",
    "case cerfa.co_log_5p_nb when 't' then 'Oui' else 'Non' end as \"".__("co_log_5p_nb")."\"",
    "case cerfa.co_log_6p_nb when 't' then 'Oui' else 'Non' end as \"".__("co_log_6p_nb")."\"",
    "case cerfa.co_bat_niv_nb when 't' then 'Oui' else 'Non' end as \"".__("co_bat_niv_nb")."\"",
    "case cerfa.co_trx_exten when 't' then 'Oui' else 'Non' end as \"".__("co_trx_exten")."\"",
    "case cerfa.co_trx_surelev when 't' then 'Oui' else 'Non' end as \"".__("co_trx_surelev")."\"",
    "case cerfa.co_trx_nivsup when 't' then 'Oui' else 'Non' end as \"".__("co_trx_nivsup")."\"",
    "case cerfa.co_demont_periode when 't' then 'Oui' else 'Non' end as \"".__("co_demont_periode")."\"",
    "case cerfa.co_sp_transport when 't' then 'Oui' else 'Non' end as \"".__("co_sp_transport")."\"",
    "case cerfa.co_sp_enseign when 't' then 'Oui' else 'Non' end as \"".__("co_sp_enseign")."\"",
    "case cerfa.co_sp_act_soc when 't' then 'Oui' else 'Non' end as \"".__("co_sp_act_soc")."\"",
    "case cerfa.co_sp_ouvr_spe when 't' then 'Oui' else 'Non' end as \"".__("co_sp_ouvr_spe")."\"",
    "case cerfa.co_sp_sante when 't' then 'Oui' else 'Non' end as \"".__("co_sp_sante")."\"",
    "case cerfa.co_sp_culture when 't' then 'Oui' else 'Non' end as \"".__("co_sp_culture")."\"",
    "case cerfa.co_statio_avt_nb when 't' then 'Oui' else 'Non' end as \"".__("co_statio_avt_nb")."\"",
    "case cerfa.co_statio_apr_nb when 't' then 'Oui' else 'Non' end as \"".__("co_statio_apr_nb")."\"",
    "case cerfa.co_statio_adr when 't' then 'Oui' else 'Non' end as \"".__("co_statio_adr")."\"",
    "case cerfa.co_statio_place_nb when 't' then 'Oui' else 'Non' end as \"".__("co_statio_place_nb")."\"",
    "case cerfa.co_statio_tot_surf when 't' then 'Oui' else 'Non' end as \"".__("co_statio_tot_surf")."\"",
    "case cerfa.co_statio_tot_shob when 't' then 'Oui' else 'Non' end as \"".__("co_statio_tot_shob")."\"",
    "case cerfa.co_statio_comm_cin_surf when 't' then 'Oui' else 'Non' end as \"".__("co_statio_comm_cin_surf")."\"",
    'cerfa.tab_surface as "'.__("tab_surface").'"',
    "case cerfa.dm_constr_dates when 't' then 'Oui' else 'Non' end as \"".__("dm_constr_dates")."\"",
    "case cerfa.dm_total when 't' then 'Oui' else 'Non' end as \"".__("dm_total")."\"",
    "case cerfa.dm_partiel when 't' then 'Oui' else 'Non' end as \"".__("dm_partiel")."\"",
    "case cerfa.dm_projet_desc when 't' then 'Oui' else 'Non' end as \"".__("dm_projet_desc")."\"",
    "case cerfa.dm_tot_log_nb when 't' then 'Oui' else 'Non' end as \"".__("dm_tot_log_nb")."\"",
    "case cerfa.tax_surf_tot when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_tot")."\"",
    "case cerfa.tax_surf when 't' then 'Oui' else 'Non' end as \"".__("tax_surf")."\"",
    "case cerfa.tax_surf_suppr_mod when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_suppr_mod")."\"",
    'cerfa.tab_tax_su_princ as "'.__("tab_tax_su_princ").'"',
    'cerfa.tab_tax_su_heber as "'.__("tab_tax_su_heber").'"',
    'cerfa.tab_tax_su_secon as "'.__("tab_tax_su_secon").'"',
    'cerfa.tab_tax_su_tot as "'.__("tab_tax_su_tot").'"',
    "case cerfa.tax_ext_pret when 't' then 'Oui' else 'Non' end as \"".__("tax_ext_pret")."\"",
    "case cerfa.tax_ext_desc when 't' then 'Oui' else 'Non' end as \"".__("tax_ext_desc")."\"",
    "case cerfa.tax_surf_tax_exist_cons when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_tax_exist_cons")."\"",
    "case cerfa.tax_log_exist_nb when 't' then 'Oui' else 'Non' end as \"".__("tax_log_exist_nb")."\"",
    "case cerfa.tax_trx_presc_ppr when 't' then 'Oui' else 'Non' end as \"".__("tax_trx_presc_ppr")."\"",
    "case cerfa.tax_monu_hist when 't' then 'Oui' else 'Non' end as \"".__("tax_monu_hist")."\"",
    "case cerfa.tax_comm_nb when 't' then 'Oui' else 'Non' end as \"".__("tax_comm_nb")."\"",
    'cerfa.tab_tax_su_non_habit_surf as "'.__("tab_tax_su_non_habit_surf").'"',
    'cerfa.tab_tax_am as "'.__("tab_tax_am").'"',
    "case cerfa.vsd_surf_planch_smd when 't' then 'Oui' else 'Non' end as \"".__("vsd_surf_planch_smd")."\"",
    "case cerfa.vsd_unit_fonc_sup when 't' then 'Oui' else 'Non' end as \"".__("vsd_unit_fonc_sup")."\"",
    "case cerfa.vsd_unit_fonc_constr_sup when 't' then 'Oui' else 'Non' end as \"".__("vsd_unit_fonc_constr_sup")."\"",
    "case cerfa.vsd_val_terr when 't' then 'Oui' else 'Non' end as \"".__("vsd_val_terr")."\"",
    "case cerfa.vsd_const_sxist_non_dem_surf when 't' then 'Oui' else 'Non' end as \"".__("vsd_const_sxist_non_dem_surf")."\"",
    "case cerfa.vsd_rescr_fisc when 't' then 'Oui' else 'Non' end as \"".__("vsd_rescr_fisc")."\"",
    "case cerfa.pld_val_terr when 't' then 'Oui' else 'Non' end as \"".__("pld_val_terr")."\"",
    "case cerfa.pld_const_exist_dem when 't' then 'Oui' else 'Non' end as \"".__("pld_const_exist_dem")."\"",
    "case cerfa.pld_const_exist_dem_surf when 't' then 'Oui' else 'Non' end as \"".__("pld_const_exist_dem_surf")."\"",
    "case cerfa.code_cnil when 't' then 'Oui' else 'Non' end as \"".__("code_cnil")."\"",
    "case cerfa.terr_juri_titul when 't' then 'Oui' else 'Non' end as \"".__("terr_juri_titul")."\"",
    "case cerfa.terr_juri_lot when 't' then 'Oui' else 'Non' end as \"".__("terr_juri_lot")."\"",
    "case cerfa.terr_juri_zac when 't' then 'Oui' else 'Non' end as \"".__("terr_juri_zac")."\"",
    "case cerfa.terr_juri_afu when 't' then 'Oui' else 'Non' end as \"".__("terr_juri_afu")."\"",
    "case cerfa.terr_juri_pup when 't' then 'Oui' else 'Non' end as \"".__("terr_juri_pup")."\"",
    "case cerfa.terr_juri_oin when 't' then 'Oui' else 'Non' end as \"".__("terr_juri_oin")."\"",
    "case cerfa.terr_juri_desc when 't' then 'Oui' else 'Non' end as \"".__("terr_juri_desc")."\"",
    "case cerfa.terr_div_surf_etab when 't' then 'Oui' else 'Non' end as \"".__("terr_div_surf_etab")."\"",
    "case cerfa.terr_div_surf_av_div when 't' then 'Oui' else 'Non' end as \"".__("terr_div_surf_av_div")."\"",
    "case cerfa.doc_date when 't' then 'Oui' else 'Non' end as \"".__("doc_date")."\"",
    "case cerfa.doc_tot_trav when 't' then 'Oui' else 'Non' end as \"".__("doc_tot_trav")."\"",
    "case cerfa.doc_tranche_trav when 't' then 'Oui' else 'Non' end as \"".__("doc_tranche_trav")."\"",
    "case cerfa.doc_tranche_trav_desc when 't' then 'Oui' else 'Non' end as \"".__("doc_tranche_trav_desc")."\"",
    "case cerfa.doc_surf when 't' then 'Oui' else 'Non' end as \"".__("doc_surf")."\"",
    "case cerfa.doc_nb_log when 't' then 'Oui' else 'Non' end as \"".__("doc_nb_log")."\"",
    "case cerfa.doc_nb_log_indiv when 't' then 'Oui' else 'Non' end as \"".__("doc_nb_log_indiv")."\"",
    "case cerfa.doc_nb_log_coll when 't' then 'Oui' else 'Non' end as \"".__("doc_nb_log_coll")."\"",
    "case cerfa.doc_nb_log_lls when 't' then 'Oui' else 'Non' end as \"".__("doc_nb_log_lls")."\"",
    "case cerfa.doc_nb_log_aa when 't' then 'Oui' else 'Non' end as \"".__("doc_nb_log_aa")."\"",
    "case cerfa.doc_nb_log_ptz when 't' then 'Oui' else 'Non' end as \"".__("doc_nb_log_ptz")."\"",
    "case cerfa.doc_nb_log_autre when 't' then 'Oui' else 'Non' end as \"".__("doc_nb_log_autre")."\"",
    "case cerfa.daact_date when 't' then 'Oui' else 'Non' end as \"".__("daact_date")."\"",
    "case cerfa.daact_date_chgmt_dest when 't' then 'Oui' else 'Non' end as \"".__("daact_date_chgmt_dest")."\"",
    "case cerfa.daact_tot_trav when 't' then 'Oui' else 'Non' end as \"".__("daact_tot_trav")."\"",
    "case cerfa.daact_tranche_trav when 't' then 'Oui' else 'Non' end as \"".__("daact_tranche_trav")."\"",
    "case cerfa.daact_tranche_trav_desc when 't' then 'Oui' else 'Non' end as \"".__("daact_tranche_trav_desc")."\"",
    "case cerfa.daact_surf when 't' then 'Oui' else 'Non' end as \"".__("daact_surf")."\"",
    "case cerfa.daact_nb_log when 't' then 'Oui' else 'Non' end as \"".__("daact_nb_log")."\"",
    "case cerfa.daact_nb_log_indiv when 't' then 'Oui' else 'Non' end as \"".__("daact_nb_log_indiv")."\"",
    "case cerfa.daact_nb_log_coll when 't' then 'Oui' else 'Non' end as \"".__("daact_nb_log_coll")."\"",
    "case cerfa.daact_nb_log_lls when 't' then 'Oui' else 'Non' end as \"".__("daact_nb_log_lls")."\"",
    "case cerfa.daact_nb_log_aa when 't' then 'Oui' else 'Non' end as \"".__("daact_nb_log_aa")."\"",
    "case cerfa.daact_nb_log_ptz when 't' then 'Oui' else 'Non' end as \"".__("daact_nb_log_ptz")."\"",
    "case cerfa.daact_nb_log_autre when 't' then 'Oui' else 'Non' end as \"".__("daact_nb_log_autre")."\"",
    "case cerfa.am_div_mun when 't' then 'Oui' else 'Non' end as \"".__("am_div_mun")."\"",
    "case cerfa.co_perf_energ when 't' then 'Oui' else 'Non' end as \"".__("co_perf_energ")."\"",
    "case cerfa.architecte when 't' then 'Oui' else 'Non' end as \"".__("architecte")."\"",
    "case cerfa.co_statio_avt_shob when 't' then 'Oui' else 'Non' end as \"".__("co_statio_avt_shob")."\"",
    "case cerfa.co_statio_apr_shob when 't' then 'Oui' else 'Non' end as \"".__("co_statio_apr_shob")."\"",
    "case cerfa.co_statio_avt_surf when 't' then 'Oui' else 'Non' end as \"".__("co_statio_avt_surf")."\"",
    "case cerfa.co_statio_apr_surf when 't' then 'Oui' else 'Non' end as \"".__("co_statio_apr_surf")."\"",
    "case cerfa.co_trx_amgt when 't' then 'Oui' else 'Non' end as \"".__("co_trx_amgt")."\"",
    "case cerfa.co_modif_aspect when 't' then 'Oui' else 'Non' end as \"".__("co_modif_aspect")."\"",
    "case cerfa.co_modif_struct when 't' then 'Oui' else 'Non' end as \"".__("co_modif_struct")."\"",
    "case cerfa.co_ouvr_elec when 't' then 'Oui' else 'Non' end as \"".__("co_ouvr_elec")."\"",
    "case cerfa.co_ouvr_infra when 't' then 'Oui' else 'Non' end as \"".__("co_ouvr_infra")."\"",
    "case cerfa.co_trx_imm when 't' then 'Oui' else 'Non' end as \"".__("co_trx_imm")."\"",
    "case cerfa.co_cstr_shob when 't' then 'Oui' else 'Non' end as \"".__("co_cstr_shob")."\"",
    "case cerfa.am_voyage_deb when 't' then 'Oui' else 'Non' end as \"".__("am_voyage_deb")."\"",
    "case cerfa.am_voyage_fin when 't' then 'Oui' else 'Non' end as \"".__("am_voyage_fin")."\"",
    "case cerfa.am_modif_amgt when 't' then 'Oui' else 'Non' end as \"".__("am_modif_amgt")."\"",
    "case cerfa.am_lot_max_shob when 't' then 'Oui' else 'Non' end as \"".__("am_lot_max_shob")."\"",
    "case cerfa.mod_desc when 't' then 'Oui' else 'Non' end as \"".__("mod_desc")."\"",
    "case cerfa.tr_total when 't' then 'Oui' else 'Non' end as \"".__("tr_total")."\"",
    "case cerfa.tr_partiel when 't' then 'Oui' else 'Non' end as \"".__("tr_partiel")."\"",
    "case cerfa.tr_desc when 't' then 'Oui' else 'Non' end as \"".__("tr_desc")."\"",
    "case cerfa.avap_co_elt_pro when 't' then 'Oui' else 'Non' end as \"".__("avap_co_elt_pro")."\"",
    "case cerfa.avap_nouv_haut_surf when 't' then 'Oui' else 'Non' end as \"".__("avap_nouv_haut_surf")."\"",
    "case cerfa.avap_co_clot when 't' then 'Oui' else 'Non' end as \"".__("avap_co_clot")."\"",
    "case cerfa.avap_aut_coup_aba_arb when 't' then 'Oui' else 'Non' end as \"".__("avap_aut_coup_aba_arb")."\"",
    "case cerfa.avap_ouv_infra when 't' then 'Oui' else 'Non' end as \"".__("avap_ouv_infra")."\"",
    "case cerfa.avap_aut_inst_mob when 't' then 'Oui' else 'Non' end as \"".__("avap_aut_inst_mob")."\"",
    "case cerfa.avap_aut_plant when 't' then 'Oui' else 'Non' end as \"".__("avap_aut_plant")."\"",
    "case cerfa.avap_aut_auv_elec when 't' then 'Oui' else 'Non' end as \"".__("avap_aut_auv_elec")."\"",
    "case cerfa.tax_dest_loc_tr when 't' then 'Oui' else 'Non' end as \"".__("tax_dest_loc_tr")."\"",
    "case cerfa.ope_proj_desc when 't' then 'Oui' else 'Non' end as \"".__("ope_proj_desc")."\"",
    "case cerfa.tax_surf_tot_cstr when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_tot_cstr")."\"",
    "case cerfa.tax_surf_loc_stat when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_loc_stat")."\"",
    "case cerfa.tax_log_ap_trvx_nb when 't' then 'Oui' else 'Non' end as \"".__("tax_log_ap_trvx_nb")."\"",
    "case cerfa.tax_am_statio_ext_cr when 't' then 'Oui' else 'Non' end as \"".__("tax_am_statio_ext_cr")."\"",
    "case cerfa.tax_sup_bass_pisc_cr when 't' then 'Oui' else 'Non' end as \"".__("tax_sup_bass_pisc_cr")."\"",
    "case cerfa.tax_empl_ten_carav_mobil_nb_cr when 't' then 'Oui' else 'Non' end as \"".__("tax_empl_ten_carav_mobil_nb_cr")."\"",
    "case cerfa.tax_empl_hll_nb_cr when 't' then 'Oui' else 'Non' end as \"".__("tax_empl_hll_nb_cr")."\"",
    "case cerfa.tax_eol_haut_nb_cr when 't' then 'Oui' else 'Non' end as \"".__("tax_eol_haut_nb_cr")."\"",
    "case cerfa.tax_pann_volt_sup_cr when 't' then 'Oui' else 'Non' end as \"".__("tax_pann_volt_sup_cr")."\"",
    "case cerfa.tax_surf_loc_arch when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_loc_arch")."\"",
    "case cerfa.tax_surf_pisc_arch when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_pisc_arch")."\"",
    "case cerfa.tax_am_statio_ext_arch when 't' then 'Oui' else 'Non' end as \"".__("tax_am_statio_ext_arch")."\"",
    'cerfa.tab_tax_su_parc_statio_expl_comm as "'.__("tab_tax_su_parc_statio_expl_comm").'"',
    "case cerfa.tax_empl_ten_carav_mobil_nb_arch when 't' then 'Oui' else 'Non' end as \"".__("tax_empl_ten_carav_mobil_nb_arch")."\"",
    "case cerfa.tax_empl_hll_nb_arch when 't' then 'Oui' else 'Non' end as \"".__("tax_empl_hll_nb_arch")."\"",
    "case cerfa.tax_eol_haut_nb_arch when 't' then 'Oui' else 'Non' end as \"".__("tax_eol_haut_nb_arch")."\"",
    "case cerfa.ope_proj_div_co when 't' then 'Oui' else 'Non' end as \"".__("ope_proj_div_co")."\"",
    "case cerfa.ope_proj_div_contr when 't' then 'Oui' else 'Non' end as \"".__("ope_proj_div_contr")."\"",
    "case cerfa.tax_desc when 't' then 'Oui' else 'Non' end as \"".__("tax_desc")."\"",
    "case cerfa.erp_cstr_neuve when 't' then 'Oui' else 'Non' end as \"".__("erp_cstr_neuve")."\"",
    "case cerfa.erp_trvx_acc when 't' then 'Oui' else 'Non' end as \"".__("erp_trvx_acc")."\"",
    "case cerfa.erp_extension when 't' then 'Oui' else 'Non' end as \"".__("erp_extension")."\"",
    "case cerfa.erp_rehab when 't' then 'Oui' else 'Non' end as \"".__("erp_rehab")."\"",
    "case cerfa.erp_trvx_am when 't' then 'Oui' else 'Non' end as \"".__("erp_trvx_am")."\"",
    "case cerfa.erp_vol_nouv_exist when 't' then 'Oui' else 'Non' end as \"".__("erp_vol_nouv_exist")."\"",
    'cerfa.tab_erp_eff as "'.__("tab_erp_eff").'"',
    "case cerfa.erp_class_cat when 't' then 'Oui' else 'Non' end as \"".__("erp_class_cat")."\"",
    "case cerfa.erp_class_type when 't' then 'Oui' else 'Non' end as \"".__("erp_class_type")."\"",
    "case cerfa.tax_surf_abr_jard_pig_colom when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_abr_jard_pig_colom")."\"",
    "case cerfa.tax_su_non_habit_abr_jard_pig_colom when 't' then 'Oui' else 'Non' end as \"".__("tax_su_non_habit_abr_jard_pig_colom")."\"",
    "case cerfa.dia_imm_non_bati when 't' then 'Oui' else 'Non' end as \"".__("dia_imm_non_bati")."\"",
    "case cerfa.dia_imm_bati_terr_propr when 't' then 'Oui' else 'Non' end as \"".__("dia_imm_bati_terr_propr")."\"",
    "case cerfa.dia_imm_bati_terr_autr when 't' then 'Oui' else 'Non' end as \"".__("dia_imm_bati_terr_autr")."\"",
    "case cerfa.dia_imm_bati_terr_autr_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_imm_bati_terr_autr_desc")."\"",
    "case cerfa.dia_bat_copro when 't' then 'Oui' else 'Non' end as \"".__("dia_bat_copro")."\"",
    "case cerfa.dia_bat_copro_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_bat_copro_desc")."\"",
    "case cerfa.dia_lot_numero when 't' then 'Oui' else 'Non' end as \"".__("dia_lot_numero")."\"",
    "case cerfa.dia_lot_bat when 't' then 'Oui' else 'Non' end as \"".__("dia_lot_bat")."\"",
    "case cerfa.dia_lot_etage when 't' then 'Oui' else 'Non' end as \"".__("dia_lot_etage")."\"",
    "case cerfa.dia_lot_quote_part when 't' then 'Oui' else 'Non' end as \"".__("dia_lot_quote_part")."\"",
    "case cerfa.dia_us_hab when 't' then 'Oui' else 'Non' end as \"".__("dia_us_hab")."\"",
    "case cerfa.dia_us_pro when 't' then 'Oui' else 'Non' end as \"".__("dia_us_pro")."\"",
    "case cerfa.dia_us_mixte when 't' then 'Oui' else 'Non' end as \"".__("dia_us_mixte")."\"",
    "case cerfa.dia_us_comm when 't' then 'Oui' else 'Non' end as \"".__("dia_us_comm")."\"",
    "case cerfa.dia_us_agr when 't' then 'Oui' else 'Non' end as \"".__("dia_us_agr")."\"",
    "case cerfa.dia_us_autre when 't' then 'Oui' else 'Non' end as \"".__("dia_us_autre")."\"",
    "case cerfa.dia_us_autre_prec when 't' then 'Oui' else 'Non' end as \"".__("dia_us_autre_prec")."\"",
    "case cerfa.dia_occ_prop when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_prop")."\"",
    "case cerfa.dia_occ_loc when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_loc")."\"",
    "case cerfa.dia_occ_sans_occ when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sans_occ")."\"",
    "case cerfa.dia_occ_autre when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_autre")."\"",
    "case cerfa.dia_occ_autre_prec when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_autre_prec")."\"",
    "case cerfa.dia_mod_cess_prix_vente when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente")."\"",
    "case cerfa.dia_mod_cess_prix_vente_mob when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente_mob")."\"",
    "case cerfa.dia_mod_cess_prix_vente_cheptel when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente_cheptel")."\"",
    "case cerfa.dia_mod_cess_prix_vente_recol when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente_recol")."\"",
    "case cerfa.dia_mod_cess_prix_vente_autre when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente_autre")."\"",
    "case cerfa.dia_mod_cess_commi when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_commi")."\"",
    "case cerfa.dia_mod_cess_commi_ttc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_commi_ttc")."\"",
    "case cerfa.dia_mod_cess_commi_ht when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_commi_ht")."\"",
    "case cerfa.dia_acquereur_nom_prenom when 't' then 'Oui' else 'Non' end as \"".__("dia_acquereur_nom_prenom")."\"",
    "case cerfa.dia_acquereur_adr_num_voie when 't' then 'Oui' else 'Non' end as \"".__("dia_acquereur_adr_num_voie")."\"",
    "case cerfa.dia_acquereur_adr_ext when 't' then 'Oui' else 'Non' end as \"".__("dia_acquereur_adr_ext")."\"",
    "case cerfa.dia_acquereur_adr_type_voie when 't' then 'Oui' else 'Non' end as \"".__("dia_acquereur_adr_type_voie")."\"",
    "case cerfa.dia_acquereur_adr_nom_voie when 't' then 'Oui' else 'Non' end as \"".__("dia_acquereur_adr_nom_voie")."\"",
    "case cerfa.dia_acquereur_adr_lieu_dit_bp when 't' then 'Oui' else 'Non' end as \"".__("dia_acquereur_adr_lieu_dit_bp")."\"",
    "case cerfa.dia_acquereur_adr_cp when 't' then 'Oui' else 'Non' end as \"".__("dia_acquereur_adr_cp")."\"",
    "case cerfa.dia_acquereur_adr_localite when 't' then 'Oui' else 'Non' end as \"".__("dia_acquereur_adr_localite")."\"",
    "case cerfa.dia_observation when 't' then 'Oui' else 'Non' end as \"".__("dia_observation")."\"",
    'cerfa.tab_surface2 as "'.__("tab_surface2").'"',
    "case cerfa.dia_occ_sol_su_terre when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_terre")."\"",
    "case cerfa.dia_occ_sol_su_pres when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_pres")."\"",
    "case cerfa.dia_occ_sol_su_verger when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_verger")."\"",
    "case cerfa.dia_occ_sol_su_vigne when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_vigne")."\"",
    "case cerfa.dia_occ_sol_su_bois when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_bois")."\"",
    "case cerfa.dia_occ_sol_su_lande when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_lande")."\"",
    "case cerfa.dia_occ_sol_su_carriere when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_carriere")."\"",
    "case cerfa.dia_occ_sol_su_eau_cadastree when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_eau_cadastree")."\"",
    "case cerfa.dia_occ_sol_su_jardin when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_jardin")."\"",
    "case cerfa.dia_occ_sol_su_terr_batir when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_terr_batir")."\"",
    "case cerfa.dia_occ_sol_su_terr_agr when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_terr_agr")."\"",
    "case cerfa.dia_occ_sol_su_sol when 't' then 'Oui' else 'Non' end as \"".__("dia_occ_sol_su_sol")."\"",
    "case cerfa.dia_bati_vend_tot when 't' then 'Oui' else 'Non' end as \"".__("dia_bati_vend_tot")."\"",
    "case cerfa.dia_bati_vend_tot_txt when 't' then 'Oui' else 'Non' end as \"".__("dia_bati_vend_tot_txt")."\"",
    "case cerfa.dia_su_co_sol when 't' then 'Oui' else 'Non' end as \"".__("dia_su_co_sol")."\"",
    "case cerfa.dia_su_util_hab when 't' then 'Oui' else 'Non' end as \"".__("dia_su_util_hab")."\"",
    "case cerfa.dia_nb_niv when 't' then 'Oui' else 'Non' end as \"".__("dia_nb_niv")."\"",
    "case cerfa.dia_nb_appart when 't' then 'Oui' else 'Non' end as \"".__("dia_nb_appart")."\"",
    "case cerfa.dia_nb_autre_loc when 't' then 'Oui' else 'Non' end as \"".__("dia_nb_autre_loc")."\"",
    "case cerfa.dia_vente_lot_volume when 't' then 'Oui' else 'Non' end as \"".__("dia_vente_lot_volume")."\"",
    "case cerfa.dia_vente_lot_volume_txt when 't' then 'Oui' else 'Non' end as \"".__("dia_vente_lot_volume_txt")."\"",
    "case cerfa.dia_lot_nat_su when 't' then 'Oui' else 'Non' end as \"".__("dia_lot_nat_su")."\"",
    "case cerfa.dia_lot_bat_achv_plus_10 when 't' then 'Oui' else 'Non' end as \"".__("dia_lot_bat_achv_plus_10")."\"",
    "case cerfa.dia_lot_bat_achv_moins_10 when 't' then 'Oui' else 'Non' end as \"".__("dia_lot_bat_achv_moins_10")."\"",
    "case cerfa.dia_lot_regl_copro_publ_hypo_plus_10 when 't' then 'Oui' else 'Non' end as \"".__("dia_lot_regl_copro_publ_hypo_plus_10")."\"",
    "case cerfa.dia_lot_regl_copro_publ_hypo_moins_10 when 't' then 'Oui' else 'Non' end as \"".__("dia_lot_regl_copro_publ_hypo_moins_10")."\"",
    "case cerfa.dia_indivi_quote_part when 't' then 'Oui' else 'Non' end as \"".__("dia_indivi_quote_part")."\"",
    "case cerfa.dia_design_societe when 't' then 'Oui' else 'Non' end as \"".__("dia_design_societe")."\"",
    "case cerfa.dia_design_droit when 't' then 'Oui' else 'Non' end as \"".__("dia_design_droit")."\"",
    "case cerfa.dia_droit_soc_nat when 't' then 'Oui' else 'Non' end as \"".__("dia_droit_soc_nat")."\"",
    "case cerfa.dia_droit_soc_nb when 't' then 'Oui' else 'Non' end as \"".__("dia_droit_soc_nb")."\"",
    "case cerfa.dia_droit_soc_num_part when 't' then 'Oui' else 'Non' end as \"".__("dia_droit_soc_num_part")."\"",
    "case cerfa.dia_droit_reel_perso_grevant_bien_oui when 't' then 'Oui' else 'Non' end as \"".__("dia_droit_reel_perso_grevant_bien_oui")."\"",
    "case cerfa.dia_droit_reel_perso_grevant_bien_non when 't' then 'Oui' else 'Non' end as \"".__("dia_droit_reel_perso_grevant_bien_non")."\"",
    "case cerfa.dia_droit_reel_perso_nat when 't' then 'Oui' else 'Non' end as \"".__("dia_droit_reel_perso_nat")."\"",
    "case cerfa.dia_droit_reel_perso_viag when 't' then 'Oui' else 'Non' end as \"".__("dia_droit_reel_perso_viag")."\"",
    "case cerfa.dia_mod_cess_adr when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_adr")."\"",
    "case cerfa.dia_mod_cess_sign_act_auth when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_sign_act_auth")."\"",
    "case cerfa.dia_mod_cess_terme when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_terme")."\"",
    "case cerfa.dia_mod_cess_terme_prec when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_terme_prec")."\"",
    "case cerfa.dia_mod_cess_bene_acquereur when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_bene_acquereur")."\"",
    "case cerfa.dia_mod_cess_bene_vendeur when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_bene_vendeur")."\"",
    "case cerfa.dia_mod_cess_paie_nat when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_paie_nat")."\"",
    "case cerfa.dia_mod_cess_design_contr_alien when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_design_contr_alien")."\"",
    "case cerfa.dia_mod_cess_eval_contr when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_eval_contr")."\"",
    "case cerfa.dia_mod_cess_rente_viag when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_rente_viag")."\"",
    "case cerfa.dia_mod_cess_mnt_an when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_mnt_an")."\"",
    "case cerfa.dia_mod_cess_mnt_compt when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_mnt_compt")."\"",
    "case cerfa.dia_mod_cess_bene_rente when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_bene_rente")."\"",
    "case cerfa.dia_mod_cess_droit_usa_hab when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_droit_usa_hab")."\"",
    "case cerfa.dia_mod_cess_droit_usa_hab_prec when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_droit_usa_hab_prec")."\"",
    "case cerfa.dia_mod_cess_eval_usa_usufruit when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_eval_usa_usufruit")."\"",
    "case cerfa.dia_mod_cess_vente_nue_prop when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_vente_nue_prop")."\"",
    "case cerfa.dia_mod_cess_vente_nue_prop_prec when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_vente_nue_prop_prec")."\"",
    "case cerfa.dia_mod_cess_echange when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_echange")."\"",
    "case cerfa.dia_mod_cess_design_bien_recus_ech when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_design_bien_recus_ech")."\"",
    "case cerfa.dia_mod_cess_mnt_soulte when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_mnt_soulte")."\"",
    "case cerfa.dia_mod_cess_prop_contre_echan when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prop_contre_echan")."\"",
    "case cerfa.dia_mod_cess_apport_societe when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_apport_societe")."\"",
    "case cerfa.dia_mod_cess_bene when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_bene")."\"",
    "case cerfa.dia_mod_cess_esti_bien when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_esti_bien")."\"",
    "case cerfa.dia_mod_cess_cess_terr_loc_co when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_cess_terr_loc_co")."\"",
    "case cerfa.dia_mod_cess_esti_terr when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_esti_terr")."\"",
    "case cerfa.dia_mod_cess_esti_loc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_esti_loc")."\"",
    "case cerfa.dia_mod_cess_esti_imm_loca when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_esti_imm_loca")."\"",
    "case cerfa.dia_mod_cess_adju_vol when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_adju_vol")."\"",
    "case cerfa.dia_mod_cess_adju_obl when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_adju_obl")."\"",
    "case cerfa.dia_mod_cess_adju_fin_indivi when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_adju_fin_indivi")."\"",
    "case cerfa.dia_mod_cess_adju_date_lieu when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_adju_date_lieu")."\"",
    "case cerfa.dia_mod_cess_mnt_mise_prix when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_mnt_mise_prix")."\"",
    "case cerfa.dia_prop_titu_prix_indique when 't' then 'Oui' else 'Non' end as \"".__("dia_prop_titu_prix_indique")."\"",
    "case cerfa.dia_prop_recherche_acqu_prix_indique when 't' then 'Oui' else 'Non' end as \"".__("dia_prop_recherche_acqu_prix_indique")."\"",
    "case cerfa.dia_acquereur_prof when 't' then 'Oui' else 'Non' end as \"".__("dia_acquereur_prof")."\"",
    "case cerfa.dia_indic_compl_ope when 't' then 'Oui' else 'Non' end as \"".__("dia_indic_compl_ope")."\"",
    "case cerfa.dia_vente_adju when 't' then 'Oui' else 'Non' end as \"".__("dia_vente_adju")."\"",
    "case cerfa.am_terr_res_demon when 't' then 'Oui' else 'Non' end as \"".__("am_terr_res_demon")."\"",
    "case cerfa.am_air_terr_res_mob when 't' then 'Oui' else 'Non' end as \"".__("am_air_terr_res_mob")."\"",
    "case cerfa.ctx_objet_recours when 't' then 'Oui' else 'Non' end as \"".__("ctx_objet_recours")."\"",
    "case cerfa.ctx_moyen_souleve when 't' then 'Oui' else 'Non' end as \"".__("ctx_moyen_souleve")."\"",
    "case cerfa.ctx_moyen_retenu_juge when 't' then 'Oui' else 'Non' end as \"".__("ctx_moyen_retenu_juge")."\"",
    "case cerfa.ctx_reference_sagace when 't' then 'Oui' else 'Non' end as \"".__("ctx_reference_sagace")."\"",
    "case cerfa.ctx_nature_travaux_infra_om_html when 't' then 'Oui' else 'Non' end as \"".__("ctx_nature_travaux_infra_om_html")."\"",
    "case cerfa.ctx_synthese_nti when 't' then 'Oui' else 'Non' end as \"".__("ctx_synthese_nti")."\"",
    "case cerfa.ctx_article_non_resp_om_html when 't' then 'Oui' else 'Non' end as \"".__("ctx_article_non_resp_om_html")."\"",
    "case cerfa.ctx_synthese_anr when 't' then 'Oui' else 'Non' end as \"".__("ctx_synthese_anr")."\"",
    "case cerfa.ctx_reference_parquet when 't' then 'Oui' else 'Non' end as \"".__("ctx_reference_parquet")."\"",
    "case cerfa.ctx_element_taxation when 't' then 'Oui' else 'Non' end as \"".__("ctx_element_taxation")."\"",
    "case cerfa.ctx_infraction when 't' then 'Oui' else 'Non' end as \"".__("ctx_infraction")."\"",
    "case cerfa.ctx_regularisable when 't' then 'Oui' else 'Non' end as \"".__("ctx_regularisable")."\"",
    "case cerfa.ctx_reference_courrier when 't' then 'Oui' else 'Non' end as \"".__("ctx_reference_courrier")."\"",
    "case cerfa.ctx_date_audience when 't' then 'Oui' else 'Non' end as \"".__("ctx_date_audience")."\"",
    "case cerfa.ctx_date_ajournement when 't' then 'Oui' else 'Non' end as \"".__("ctx_date_ajournement")."\"",
    "case cerfa.exo_facul_1 when 't' then 'Oui' else 'Non' end as \"".__("exo_facul_1")."\"",
    "case cerfa.exo_facul_2 when 't' then 'Oui' else 'Non' end as \"".__("exo_facul_2")."\"",
    "case cerfa.exo_facul_3 when 't' then 'Oui' else 'Non' end as \"".__("exo_facul_3")."\"",
    "case cerfa.exo_facul_4 when 't' then 'Oui' else 'Non' end as \"".__("exo_facul_4")."\"",
    "case cerfa.exo_facul_5 when 't' then 'Oui' else 'Non' end as \"".__("exo_facul_5")."\"",
    "case cerfa.exo_facul_6 when 't' then 'Oui' else 'Non' end as \"".__("exo_facul_6")."\"",
    "case cerfa.exo_facul_7 when 't' then 'Oui' else 'Non' end as \"".__("exo_facul_7")."\"",
    "case cerfa.exo_facul_8 when 't' then 'Oui' else 'Non' end as \"".__("exo_facul_8")."\"",
    "case cerfa.exo_facul_9 when 't' then 'Oui' else 'Non' end as \"".__("exo_facul_9")."\"",
    "case cerfa.exo_ta_1 when 't' then 'Oui' else 'Non' end as \"".__("exo_ta_1")."\"",
    "case cerfa.exo_ta_2 when 't' then 'Oui' else 'Non' end as \"".__("exo_ta_2")."\"",
    "case cerfa.exo_ta_3 when 't' then 'Oui' else 'Non' end as \"".__("exo_ta_3")."\"",
    "case cerfa.exo_ta_4 when 't' then 'Oui' else 'Non' end as \"".__("exo_ta_4")."\"",
    "case cerfa.exo_ta_5 when 't' then 'Oui' else 'Non' end as \"".__("exo_ta_5")."\"",
    "case cerfa.exo_ta_6 when 't' then 'Oui' else 'Non' end as \"".__("exo_ta_6")."\"",
    "case cerfa.exo_ta_7 when 't' then 'Oui' else 'Non' end as \"".__("exo_ta_7")."\"",
    "case cerfa.exo_ta_8 when 't' then 'Oui' else 'Non' end as \"".__("exo_ta_8")."\"",
    "case cerfa.exo_ta_9 when 't' then 'Oui' else 'Non' end as \"".__("exo_ta_9")."\"",
    "case cerfa.exo_rap_1 when 't' then 'Oui' else 'Non' end as \"".__("exo_rap_1")."\"",
    "case cerfa.exo_rap_2 when 't' then 'Oui' else 'Non' end as \"".__("exo_rap_2")."\"",
    "case cerfa.exo_rap_3 when 't' then 'Oui' else 'Non' end as \"".__("exo_rap_3")."\"",
    "case cerfa.exo_rap_4 when 't' then 'Oui' else 'Non' end as \"".__("exo_rap_4")."\"",
    "case cerfa.exo_rap_5 when 't' then 'Oui' else 'Non' end as \"".__("exo_rap_5")."\"",
    "case cerfa.exo_rap_6 when 't' then 'Oui' else 'Non' end as \"".__("exo_rap_6")."\"",
    "case cerfa.exo_rap_7 when 't' then 'Oui' else 'Non' end as \"".__("exo_rap_7")."\"",
    "case cerfa.exo_rap_8 when 't' then 'Oui' else 'Non' end as \"".__("exo_rap_8")."\"",
    "case cerfa.mtn_exo_ta_part_commu when 't' then 'Oui' else 'Non' end as \"".__("mtn_exo_ta_part_commu")."\"",
    "case cerfa.mtn_exo_ta_part_depart when 't' then 'Oui' else 'Non' end as \"".__("mtn_exo_ta_part_depart")."\"",
    "case cerfa.mtn_exo_ta_part_reg when 't' then 'Oui' else 'Non' end as \"".__("mtn_exo_ta_part_reg")."\"",
    "case cerfa.mtn_exo_rap when 't' then 'Oui' else 'Non' end as \"".__("mtn_exo_rap")."\"",
    "case cerfa.dpc_type when 't' then 'Oui' else 'Non' end as \"".__("dpc_type")."\"",
    "case cerfa.dpc_desc_actv_ex when 't' then 'Oui' else 'Non' end as \"".__("dpc_desc_actv_ex")."\"",
    "case cerfa.dpc_desc_ca when 't' then 'Oui' else 'Non' end as \"".__("dpc_desc_ca")."\"",
    "case cerfa.dpc_desc_aut_prec when 't' then 'Oui' else 'Non' end as \"".__("dpc_desc_aut_prec")."\"",
    "case cerfa.dpc_desig_comm_arti when 't' then 'Oui' else 'Non' end as \"".__("dpc_desig_comm_arti")."\"",
    "case cerfa.dpc_desig_loc_hab when 't' then 'Oui' else 'Non' end as \"".__("dpc_desig_loc_hab")."\"",
    "case cerfa.dpc_desig_loc_ann when 't' then 'Oui' else 'Non' end as \"".__("dpc_desig_loc_ann")."\"",
    "case cerfa.dpc_desig_loc_ann_prec when 't' then 'Oui' else 'Non' end as \"".__("dpc_desig_loc_ann_prec")."\"",
    "case cerfa.dpc_bail_comm_date when 't' then 'Oui' else 'Non' end as \"".__("dpc_bail_comm_date")."\"",
    "case cerfa.dpc_bail_comm_loyer when 't' then 'Oui' else 'Non' end as \"".__("dpc_bail_comm_loyer")."\"",
    "case cerfa.dpc_actv_acqu when 't' then 'Oui' else 'Non' end as \"".__("dpc_actv_acqu")."\"",
    "case cerfa.dpc_nb_sala_di when 't' then 'Oui' else 'Non' end as \"".__("dpc_nb_sala_di")."\"",
    "case cerfa.dpc_nb_sala_dd when 't' then 'Oui' else 'Non' end as \"".__("dpc_nb_sala_dd")."\"",
    "case cerfa.dpc_nb_sala_tc when 't' then 'Oui' else 'Non' end as \"".__("dpc_nb_sala_tc")."\"",
    "case cerfa.dpc_nb_sala_tp when 't' then 'Oui' else 'Non' end as \"".__("dpc_nb_sala_tp")."\"",
    "case cerfa.dpc_moda_cess_vente_am when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_vente_am")."\"",
    "case cerfa.dpc_moda_cess_adj when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_adj")."\"",
    "case cerfa.dpc_moda_cess_prix when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_prix")."\"",
    "case cerfa.dpc_moda_cess_adj_date when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_adj_date")."\"",
    "case cerfa.dpc_moda_cess_adj_prec when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_adj_prec")."\"",
    "case cerfa.dpc_moda_cess_paie_comp when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_comp")."\"",
    "case cerfa.dpc_moda_cess_paie_terme when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_terme")."\"",
    "case cerfa.dpc_moda_cess_paie_terme_prec when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_terme_prec")."\"",
    "case cerfa.dpc_moda_cess_paie_nat when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_nat")."\"",
    "case cerfa.dpc_moda_cess_paie_nat_desig_alien when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_nat_desig_alien")."\"",
    "case cerfa.dpc_moda_cess_paie_nat_desig_alien_prec when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_nat_desig_alien_prec")."\"",
    "case cerfa.dpc_moda_cess_paie_nat_eval when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_nat_eval")."\"",
    "case cerfa.dpc_moda_cess_paie_nat_eval_prec when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_nat_eval_prec")."\"",
    "case cerfa.dpc_moda_cess_paie_aut when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_aut")."\"",
    "case cerfa.dpc_moda_cess_paie_aut_prec when 't' then 'Oui' else 'Non' end as \"".__("dpc_moda_cess_paie_aut_prec")."\"",
    "case cerfa.dpc_ss_signe_demande_acqu when 't' then 'Oui' else 'Non' end as \"".__("dpc_ss_signe_demande_acqu")."\"",
    "case cerfa.dpc_ss_signe_recher_trouv_acqu when 't' then 'Oui' else 'Non' end as \"".__("dpc_ss_signe_recher_trouv_acqu")."\"",
    "case cerfa.dpc_notif_adr_prop when 't' then 'Oui' else 'Non' end as \"".__("dpc_notif_adr_prop")."\"",
    "case cerfa.dpc_notif_adr_manda when 't' then 'Oui' else 'Non' end as \"".__("dpc_notif_adr_manda")."\"",
    "case cerfa.dpc_obs when 't' then 'Oui' else 'Non' end as \"".__("dpc_obs")."\"",
    "case cerfa.co_peri_site_patri_remar when 't' then 'Oui' else 'Non' end as \"".__("co_peri_site_patri_remar")."\"",
    "case cerfa.co_abo_monu_hist when 't' then 'Oui' else 'Non' end as \"".__("co_abo_monu_hist")."\"",
    "case cerfa.co_inst_ouvr_trav_act_code_envir when 't' then 'Oui' else 'Non' end as \"".__("co_inst_ouvr_trav_act_code_envir")."\"",
    "case cerfa.co_trav_auto_env when 't' then 'Oui' else 'Non' end as \"".__("co_trav_auto_env")."\"",
    "case cerfa.co_derog_esp_prot when 't' then 'Oui' else 'Non' end as \"".__("co_derog_esp_prot")."\"",
    "case cerfa.ctx_reference_dsj when 't' then 'Oui' else 'Non' end as \"".__("ctx_reference_dsj")."\"",
    "case cerfa.co_piscine when 't' then 'Oui' else 'Non' end as \"".__("co_piscine")."\"",
    "case cerfa.co_fin_lls when 't' then 'Oui' else 'Non' end as \"".__("co_fin_lls")."\"",
    "case cerfa.co_fin_aa when 't' then 'Oui' else 'Non' end as \"".__("co_fin_aa")."\"",
    "case cerfa.co_fin_ptz when 't' then 'Oui' else 'Non' end as \"".__("co_fin_ptz")."\"",
    "case cerfa.co_fin_autr when 't' then 'Oui' else 'Non' end as \"".__("co_fin_autr")."\"",
    "case cerfa.dia_ss_date when 't' then 'Oui' else 'Non' end as \"".__("dia_ss_date")."\"",
    "case cerfa.dia_ss_lieu when 't' then 'Oui' else 'Non' end as \"".__("dia_ss_lieu")."\"",
    "case cerfa.enga_decla_lieu when 't' then 'Oui' else 'Non' end as \"".__("enga_decla_lieu")."\"",
    "case cerfa.enga_decla_date when 't' then 'Oui' else 'Non' end as \"".__("enga_decla_date")."\"",
    "case cerfa.co_archi_attest_honneur when 't' then 'Oui' else 'Non' end as \"".__("co_archi_attest_honneur")."\"",
    "case cerfa.co_bat_niv_dessous_nb when 't' then 'Oui' else 'Non' end as \"".__("co_bat_niv_dessous_nb")."\"",
    "case cerfa.co_install_classe when 't' then 'Oui' else 'Non' end as \"".__("co_install_classe")."\"",
    "case cerfa.co_derog_innov when 't' then 'Oui' else 'Non' end as \"".__("co_derog_innov")."\"",
    "case cerfa.co_avis_abf when 't' then 'Oui' else 'Non' end as \"".__("co_avis_abf")."\"",
    "case cerfa.tax_surf_tot_demo when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_tot_demo")."\"",
    "case cerfa.tax_surf_tax_demo when 't' then 'Oui' else 'Non' end as \"".__("tax_surf_tax_demo")."\"",
    "case cerfa.tax_terrassement_arch when 't' then 'Oui' else 'Non' end as \"".__("tax_terrassement_arch")."\"",
    "case cerfa.tax_adresse_future_numero when 't' then 'Oui' else 'Non' end as \"".__("tax_adresse_future_numero")."\"",
    "case cerfa.tax_adresse_future_voie when 't' then 'Oui' else 'Non' end as \"".__("tax_adresse_future_voie")."\"",
    "case cerfa.tax_adresse_future_lieudit when 't' then 'Oui' else 'Non' end as \"".__("tax_adresse_future_lieudit")."\"",
    "case cerfa.tax_adresse_future_localite when 't' then 'Oui' else 'Non' end as \"".__("tax_adresse_future_localite")."\"",
    "case cerfa.tax_adresse_future_cp when 't' then 'Oui' else 'Non' end as \"".__("tax_adresse_future_cp")."\"",
    "case cerfa.tax_adresse_future_bp when 't' then 'Oui' else 'Non' end as \"".__("tax_adresse_future_bp")."\"",
    "case cerfa.tax_adresse_future_cedex when 't' then 'Oui' else 'Non' end as \"".__("tax_adresse_future_cedex")."\"",
    "case cerfa.tax_adresse_future_pays when 't' then 'Oui' else 'Non' end as \"".__("tax_adresse_future_pays")."\"",
    "case cerfa.tax_adresse_future_division when 't' then 'Oui' else 'Non' end as \"".__("tax_adresse_future_division")."\"",
    "case cerfa.co_bat_projete when 't' then 'Oui' else 'Non' end as \"".__("co_bat_projete")."\"",
    "case cerfa.co_bat_existant when 't' then 'Oui' else 'Non' end as \"".__("co_bat_existant")."\"",
    "case cerfa.co_bat_nature when 't' then 'Oui' else 'Non' end as \"".__("co_bat_nature")."\"",
    "case cerfa.terr_juri_titul_date when 't' then 'Oui' else 'Non' end as \"".__("terr_juri_titul_date")."\"",
    "case cerfa.co_autre_desc when 't' then 'Oui' else 'Non' end as \"".__("co_autre_desc")."\"",
    "case cerfa.co_trx_autre when 't' then 'Oui' else 'Non' end as \"".__("co_trx_autre")."\"",
    "case cerfa.co_autre when 't' then 'Oui' else 'Non' end as \"".__("co_autre")."\"",
    "case cerfa.erp_modif_facades when 't' then 'Oui' else 'Non' end as \"".__("erp_modif_facades")."\"",
    "case cerfa.erp_trvx_adap when 't' then 'Oui' else 'Non' end as \"".__("erp_trvx_adap")."\"",
    "case cerfa.erp_trvx_adap_numero when 't' then 'Oui' else 'Non' end as \"".__("erp_trvx_adap_numero")."\"",
    "case cerfa.erp_trvx_adap_valid when 't' then 'Oui' else 'Non' end as \"".__("erp_trvx_adap_valid")."\"",
    "case cerfa.erp_prod_dangereux when 't' then 'Oui' else 'Non' end as \"".__("erp_prod_dangereux")."\"",
    "case cerfa.co_trav_supp_dessus when 't' then 'Oui' else 'Non' end as \"".__("co_trav_supp_dessus")."\"",
    "case cerfa.co_trav_supp_dessous when 't' then 'Oui' else 'Non' end as \"".__("co_trav_supp_dessous")."\"",
    "case cerfa.tax_su_habit_abr_jard_pig_colom when 't' then 'Oui' else 'Non' end as \"".__("tax_su_habit_abr_jard_pig_colom")."\"",
    "case cerfa.enga_decla_donnees_nomi_comm when 't' then 'Oui' else 'Non' end as \"".__("enga_decla_donnees_nomi_comm")."\"",
    "case cerfa.x1l_legislation when 't' then 'Oui' else 'Non' end as \"".__("x1l_legislation")."\"",
    "case cerfa.x1p_precisions when 't' then 'Oui' else 'Non' end as \"".__("x1p_precisions")."\"",
    "case cerfa.x1u_raccordement when 't' then 'Oui' else 'Non' end as \"".__("x1u_raccordement")."\"",
    "case cerfa.x2m_inscritmh when 't' then 'Oui' else 'Non' end as \"".__("x2m_inscritmh")."\"",
    "case cerfa.s1na1_numero when 't' then 'Oui' else 'Non' end as \"".__("s1na1_numero")."\"",
    "case cerfa.s1va1_voie when 't' then 'Oui' else 'Non' end as \"".__("s1va1_voie")."\"",
    "case cerfa.s1wa1_lieudit when 't' then 'Oui' else 'Non' end as \"".__("s1wa1_lieudit")."\"",
    "case cerfa.s1la1_localite when 't' then 'Oui' else 'Non' end as \"".__("s1la1_localite")."\"",
    "case cerfa.s1pa1_codepostal when 't' then 'Oui' else 'Non' end as \"".__("s1pa1_codepostal")."\"",
    "case cerfa.s1na2_numero when 't' then 'Oui' else 'Non' end as \"".__("s1na2_numero")."\"",
    "case cerfa.s1va2_voie when 't' then 'Oui' else 'Non' end as \"".__("s1va2_voie")."\"",
    "case cerfa.s1wa2_lieudit when 't' then 'Oui' else 'Non' end as \"".__("s1wa2_lieudit")."\"",
    "case cerfa.s1la2_localite when 't' then 'Oui' else 'Non' end as \"".__("s1la2_localite")."\"",
    "case cerfa.s1pa2_codepostal when 't' then 'Oui' else 'Non' end as \"".__("s1pa2_codepostal")."\"",
    "case cerfa.e3c_certification when 't' then 'Oui' else 'Non' end as \"".__("e3c_certification")."\"",
    "case cerfa.e3a_competence when 't' then 'Oui' else 'Non' end as \"".__("e3a_competence")."\"",
    "case cerfa.a4d_description when 't' then 'Oui' else 'Non' end as \"".__("a4d_description")."\"",
    "case cerfa.m2b_abf when 't' then 'Oui' else 'Non' end as \"".__("m2b_abf")."\"",
    "case cerfa.m2j_pn when 't' then 'Oui' else 'Non' end as \"".__("m2j_pn")."\"",
    "case cerfa.m2r_cdac when 't' then 'Oui' else 'Non' end as \"".__("m2r_cdac")."\"",
    "case cerfa.m2r_cnac when 't' then 'Oui' else 'Non' end as \"".__("m2r_cnac")."\"",
    "case cerfa.u3a_voirieoui when 't' then 'Oui' else 'Non' end as \"".__("u3a_voirieoui")."\"",
    "case cerfa.u3f_voirienon when 't' then 'Oui' else 'Non' end as \"".__("u3f_voirienon")."\"",
    "case cerfa.u3c_eauoui when 't' then 'Oui' else 'Non' end as \"".__("u3c_eauoui")."\"",
    "case cerfa.u3h_eaunon when 't' then 'Oui' else 'Non' end as \"".__("u3h_eaunon")."\"",
    "case cerfa.u3g_assainissementoui when 't' then 'Oui' else 'Non' end as \"".__("u3g_assainissementoui")."\"",
    "case cerfa.u3n_assainissementnon when 't' then 'Oui' else 'Non' end as \"".__("u3n_assainissementnon")."\"",
    "case cerfa.u3m_electriciteoui when 't' then 'Oui' else 'Non' end as \"".__("u3m_electriciteoui")."\"",
    "case cerfa.u3b_electricitenon when 't' then 'Oui' else 'Non' end as \"".__("u3b_electricitenon")."\"",
    "case cerfa.u3t_observations when 't' then 'Oui' else 'Non' end as \"".__("u3t_observations")."\"",
    "case cerfa.u1a_voirieoui when 't' then 'Oui' else 'Non' end as \"".__("u1a_voirieoui")."\"",
    "case cerfa.u1v_voirienon when 't' then 'Oui' else 'Non' end as \"".__("u1v_voirienon")."\"",
    "case cerfa.u1q_voirieconcessionnaire when 't' then 'Oui' else 'Non' end as \"".__("u1q_voirieconcessionnaire")."\"",
    "case cerfa.u1b_voirieavant when 't' then 'Oui' else 'Non' end as \"".__("u1b_voirieavant")."\"",
    "case cerfa.u1j_eauoui when 't' then 'Oui' else 'Non' end as \"".__("u1j_eauoui")."\"",
    "case cerfa.u1t_eaunon when 't' then 'Oui' else 'Non' end as \"".__("u1t_eaunon")."\"",
    "case cerfa.u1e_eauconcessionnaire when 't' then 'Oui' else 'Non' end as \"".__("u1e_eauconcessionnaire")."\"",
    "case cerfa.u1k_eauavant when 't' then 'Oui' else 'Non' end as \"".__("u1k_eauavant")."\"",
    "case cerfa.u1s_assainissementoui when 't' then 'Oui' else 'Non' end as \"".__("u1s_assainissementoui")."\"",
    "case cerfa.u1d_assainissementnon when 't' then 'Oui' else 'Non' end as \"".__("u1d_assainissementnon")."\"",
    "case cerfa.u1l_assainissementconcessionnaire when 't' then 'Oui' else 'Non' end as \"".__("u1l_assainissementconcessionnaire")."\"",
    "case cerfa.u1r_assainissementavant when 't' then 'Oui' else 'Non' end as \"".__("u1r_assainissementavant")."\"",
    "case cerfa.u1c_electriciteoui when 't' then 'Oui' else 'Non' end as \"".__("u1c_electriciteoui")."\"",
    "case cerfa.u1u_electricitenon when 't' then 'Oui' else 'Non' end as \"".__("u1u_electricitenon")."\"",
    "case cerfa.u1m_electriciteconcessionnaire when 't' then 'Oui' else 'Non' end as \"".__("u1m_electriciteconcessionnaire")."\"",
    "case cerfa.u1f_electriciteavant when 't' then 'Oui' else 'Non' end as \"".__("u1f_electriciteavant")."\"",
    "case cerfa.u2a_observations when 't' then 'Oui' else 'Non' end as \"".__("u2a_observations")."\"",
    "case cerfa.f1ts4_surftaxestation when 't' then 'Oui' else 'Non' end as \"".__("f1ts4_surftaxestation")."\"",
    "case cerfa.f1ut1_surfcree when 't' then 'Oui' else 'Non' end as \"".__("f1ut1_surfcree")."\"",
    "case cerfa.f9d_date when 't' then 'Oui' else 'Non' end as \"".__("f9d_date")."\"",
    "case cerfa.f9n_nom when 't' then 'Oui' else 'Non' end as \"".__("f9n_nom")."\"",
    "case cerfa.dia_droit_reel_perso_grevant_bien_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_droit_reel_perso_grevant_bien_desc")."\"",
    "case cerfa.dia_mod_cess_paie_nat_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_paie_nat_desc")."\"",
    "case cerfa.dia_mod_cess_rente_viag_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_rente_viag_desc")."\"",
    "case cerfa.dia_mod_cess_echange_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_echange_desc")."\"",
    "case cerfa.dia_mod_cess_apport_societe_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_apport_societe_desc")."\"",
    "case cerfa.dia_mod_cess_cess_terr_loc_co_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_cess_terr_loc_co_desc")."\"",
    "case cerfa.dia_mod_cess_esti_imm_loca_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_esti_imm_loca_desc")."\"",
    "case cerfa.dia_mod_cess_adju_obl_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_adju_obl_desc")."\"",
    "case cerfa.dia_mod_cess_adju_fin_indivi_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_adju_fin_indivi_desc")."\"",
    "case cerfa.dia_cadre_titul_droit_prempt when 't' then 'Oui' else 'Non' end as \"".__("dia_cadre_titul_droit_prempt")."\"",
    "case cerfa.dia_mairie_prix_moyen when 't' then 'Oui' else 'Non' end as \"".__("dia_mairie_prix_moyen")."\"",
    "case cerfa.dia_propri_indivi when 't' then 'Oui' else 'Non' end as \"".__("dia_propri_indivi")."\"",
    "case cerfa.dia_situa_bien_plan_cadas_oui when 't' then 'Oui' else 'Non' end as \"".__("dia_situa_bien_plan_cadas_oui")."\"",
    "case cerfa.dia_situa_bien_plan_cadas_non when 't' then 'Oui' else 'Non' end as \"".__("dia_situa_bien_plan_cadas_non")."\"",
    "case cerfa.dia_notif_dec_titul_adr_prop when 't' then 'Oui' else 'Non' end as \"".__("dia_notif_dec_titul_adr_prop")."\"",
    "case cerfa.dia_notif_dec_titul_adr_prop_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_notif_dec_titul_adr_prop_desc")."\"",
    "case cerfa.dia_notif_dec_titul_adr_manda when 't' then 'Oui' else 'Non' end as \"".__("dia_notif_dec_titul_adr_manda")."\"",
    "case cerfa.dia_notif_dec_titul_adr_manda_desc when 't' then 'Oui' else 'Non' end as \"".__("dia_notif_dec_titul_adr_manda_desc")."\"",
    "case cerfa.dia_dia_dpu when 't' then 'Oui' else 'Non' end as \"".__("dia_dia_dpu")."\"",
    "case cerfa.dia_dia_zad when 't' then 'Oui' else 'Non' end as \"".__("dia_dia_zad")."\"",
    "case cerfa.dia_dia_zone_preempt_esp_natu_sensi when 't' then 'Oui' else 'Non' end as \"".__("dia_dia_zone_preempt_esp_natu_sensi")."\"",
    "case cerfa.dia_dab_dpu when 't' then 'Oui' else 'Non' end as \"".__("dia_dab_dpu")."\"",
    "case cerfa.dia_dab_zad when 't' then 'Oui' else 'Non' end as \"".__("dia_dab_zad")."\"",
    "case cerfa.dia_mod_cess_commi_mnt when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_commi_mnt")."\"",
    "case cerfa.dia_mod_cess_commi_mnt_ttc when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_commi_mnt_ttc")."\"",
    "case cerfa.dia_mod_cess_commi_mnt_ht when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_commi_mnt_ht")."\"",
    "case cerfa.dia_mod_cess_prix_vente_num when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente_num")."\"",
    "case cerfa.dia_mod_cess_prix_vente_mob_num when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente_mob_num")."\"",
    "case cerfa.dia_mod_cess_prix_vente_cheptel_num when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente_cheptel_num")."\"",
    "case cerfa.dia_mod_cess_prix_vente_recol_num when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente_recol_num")."\"",
    "case cerfa.dia_mod_cess_prix_vente_autre_num when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_prix_vente_autre_num")."\"",
    "case cerfa.dia_su_co_sol_num when 't' then 'Oui' else 'Non' end as \"".__("dia_su_co_sol_num")."\"",
    "case cerfa.dia_su_util_hab_num when 't' then 'Oui' else 'Non' end as \"".__("dia_su_util_hab_num")."\"",
    "case cerfa.dia_mod_cess_mnt_an_num when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_mnt_an_num")."\"",
    "case cerfa.dia_mod_cess_mnt_compt_num when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_mnt_compt_num")."\"",
    "case cerfa.dia_mod_cess_mnt_soulte_num when 't' then 'Oui' else 'Non' end as \"".__("dia_mod_cess_mnt_soulte_num")."\"",
    "case cerfa.dia_comp_prix_vente when 't' then 'Oui' else 'Non' end as \"".__("dia_comp_prix_vente")."\"",
    "case cerfa.dia_comp_surface when 't' then 'Oui' else 'Non' end as \"".__("dia_comp_surface")."\"",
    "case cerfa.dia_comp_total_frais when 't' then 'Oui' else 'Non' end as \"".__("dia_comp_total_frais")."\"",
    "case cerfa.dia_comp_mtn_total when 't' then 'Oui' else 'Non' end as \"".__("dia_comp_mtn_total")."\"",
    "case cerfa.dia_comp_valeur_m2 when 't' then 'Oui' else 'Non' end as \"".__("dia_comp_valeur_m2")."\"",
    "case cerfa.dia_esti_prix_france_dom when 't' then 'Oui' else 'Non' end as \"".__("dia_esti_prix_france_dom")."\"",
    "case cerfa.dia_prop_collectivite when 't' then 'Oui' else 'Non' end as \"".__("dia_prop_collectivite")."\"",
    "case cerfa.dia_delegataire_denomination when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_denomination")."\"",
    "case cerfa.dia_delegataire_raison_sociale when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_raison_sociale")."\"",
    "case cerfa.dia_delegataire_siret when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_siret")."\"",
    "case cerfa.dia_delegataire_categorie_juridique when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_categorie_juridique")."\"",
    "case cerfa.dia_delegataire_representant_nom when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_representant_nom")."\"",
    "case cerfa.dia_delegataire_representant_prenom when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_representant_prenom")."\"",
    "case cerfa.dia_delegataire_adresse_numero when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_adresse_numero")."\"",
    "case cerfa.dia_delegataire_adresse_voie when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_adresse_voie")."\"",
    "case cerfa.dia_delegataire_adresse_complement when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_adresse_complement")."\"",
    "case cerfa.dia_delegataire_adresse_lieu_dit when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_adresse_lieu_dit")."\"",
    "case cerfa.dia_delegataire_adresse_localite when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_adresse_localite")."\"",
    "case cerfa.dia_delegataire_adresse_code_postal when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_adresse_code_postal")."\"",
    "case cerfa.dia_delegataire_adresse_bp when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_adresse_bp")."\"",
    "case cerfa.dia_delegataire_adresse_cedex when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_adresse_cedex")."\"",
    "case cerfa.dia_delegataire_adresse_pays when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_adresse_pays")."\"",
    "case cerfa.dia_delegataire_telephone_fixe when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_telephone_fixe")."\"",
    "case cerfa.dia_delegataire_telephone_mobile when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_telephone_mobile")."\"",
    "case cerfa.dia_delegataire_telephone_mobile_indicatif when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_telephone_mobile_indicatif")."\"",
    "case cerfa.dia_delegataire_courriel when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_courriel")."\"",
    "case cerfa.dia_delegataire_fax when 't' then 'Oui' else 'Non' end as \"".__("dia_delegataire_fax")."\"",
    "case cerfa.dia_entree_jouissance_type when 't' then 'Oui' else 'Non' end as \"".__("dia_entree_jouissance_type")."\"",
    "case cerfa.dia_entree_jouissance_date when 't' then 'Oui' else 'Non' end as \"".__("dia_entree_jouissance_date")."\"",
    "case cerfa.dia_entree_jouissance_date_effet when 't' then 'Oui' else 'Non' end as \"".__("dia_entree_jouissance_date_effet")."\"",
    "case cerfa.dia_entree_jouissance_com when 't' then 'Oui' else 'Non' end as \"".__("dia_entree_jouissance_com")."\"",
    "case cerfa.dia_remise_bien_date_effet when 't' then 'Oui' else 'Non' end as \"".__("dia_remise_bien_date_effet")."\"",
    "case cerfa.dia_remise_bien_com when 't' then 'Oui' else 'Non' end as \"".__("dia_remise_bien_com")."\"",
    "case cerfa.c2zp1_crete when 't' then 'Oui' else 'Non' end as \"".__("c2zp1_crete")."\"",
    "case cerfa.c2zr1_destination when 't' then 'Oui' else 'Non' end as \"".__("c2zr1_destination")."\"",
    "case cerfa.mh_design_appel_denom when 't' then 'Oui' else 'Non' end as \"".__("mh_design_appel_denom")."\"",
    "case cerfa.mh_design_type_protect when 't' then 'Oui' else 'Non' end as \"".__("mh_design_type_protect")."\"",
    "case cerfa.mh_design_elem_prot when 't' then 'Oui' else 'Non' end as \"".__("mh_design_elem_prot")."\"",
    "case cerfa.mh_design_ref_merimee_palissy when 't' then 'Oui' else 'Non' end as \"".__("mh_design_ref_merimee_palissy")."\"",
    "case cerfa.mh_design_nature_prop when 't' then 'Oui' else 'Non' end as \"".__("mh_design_nature_prop")."\"",
    "case cerfa.mh_loc_denom when 't' then 'Oui' else 'Non' end as \"".__("mh_loc_denom")."\"",
    "case cerfa.mh_pres_intitule when 't' then 'Oui' else 'Non' end as \"".__("mh_pres_intitule")."\"",
    "case cerfa.mh_trav_cat_1 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_1")."\"",
    "case cerfa.mh_trav_cat_2 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_2")."\"",
    "case cerfa.mh_trav_cat_3 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_3")."\"",
    "case cerfa.mh_trav_cat_4 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_4")."\"",
    "case cerfa.mh_trav_cat_5 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_5")."\"",
    "case cerfa.mh_trav_cat_6 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_6")."\"",
    "case cerfa.mh_trav_cat_7 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_7")."\"",
    "case cerfa.mh_trav_cat_8 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_8")."\"",
    "case cerfa.mh_trav_cat_9 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_9")."\"",
    "case cerfa.mh_trav_cat_10 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_10")."\"",
    "case cerfa.mh_trav_cat_11 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_11")."\"",
    "case cerfa.mh_trav_cat_12 when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_12")."\"",
    "case cerfa.mh_trav_cat_12_prec when 't' then 'Oui' else 'Non' end as \"".__("mh_trav_cat_12_prec")."\"",
    );
//
$champNonAffiche = array(
    );
//
$champRecherche = array(
    'cerfa.cerfa as "'.__("cerfa").'"',
    'cerfa.libelle as "'.__("libelle").'"',
    'cerfa.code as "'.__("code").'"',
    'cerfa.tab_surface as "'.__("tab_surface").'"',
    'cerfa.tab_tax_su_princ as "'.__("tab_tax_su_princ").'"',
    'cerfa.tab_tax_su_heber as "'.__("tab_tax_su_heber").'"',
    'cerfa.tab_tax_su_secon as "'.__("tab_tax_su_secon").'"',
    'cerfa.tab_tax_su_tot as "'.__("tab_tax_su_tot").'"',
    'cerfa.tab_tax_su_non_habit_surf as "'.__("tab_tax_su_non_habit_surf").'"',
    'cerfa.tab_tax_am as "'.__("tab_tax_am").'"',
    'cerfa.tab_tax_su_parc_statio_expl_comm as "'.__("tab_tax_su_parc_statio_expl_comm").'"',
    'cerfa.tab_erp_eff as "'.__("tab_erp_eff").'"',
    'cerfa.tab_surface2 as "'.__("tab_surface2").'"',
    );
$tri="ORDER BY cerfa.libelle ASC NULLS LAST";
$edition="cerfa";
/**
 * Gestion de la clause WHERE => $selection
 */
// Filtre listing standard
$selection = " WHERE ((cerfa.om_validite_debut IS NULL AND (cerfa.om_validite_fin IS NULL OR cerfa.om_validite_fin > CURRENT_DATE)) OR (cerfa.om_validite_debut <= CURRENT_DATE AND (cerfa.om_validite_fin IS NULL OR cerfa.om_validite_fin > CURRENT_DATE)))";
$where_om_validite = " WHERE ((cerfa.om_validite_debut IS NULL AND (cerfa.om_validite_fin IS NULL OR cerfa.om_validite_fin > CURRENT_DATE)) OR (cerfa.om_validite_debut <= CURRENT_DATE AND (cerfa.om_validite_fin IS NULL OR cerfa.om_validite_fin > CURRENT_DATE)))";
// Gestion OMValidité - Suppression du filtre si paramètre
if (isset($_GET["valide"]) and $_GET["valide"] == "false") {
    if (!isset($where_om_validite)
        or (isset($where_om_validite) and $where_om_validite == "")) {
        if (trim($selection) != "") {
            $selection = "";
        }
    } else {
        $selection = trim(str_replace($where_om_validite, "", $selection));
    }
}

/**
 * Gestion SOUSFORMULAIRE => $sousformulaire
 */
$sousformulaire = array(
    'dossier_autorisation_type_detaille',
);

