<?php
// TABLEAUX

// Destination des constructions et tableau des surfaces
$tab_surface["13409"] = array(
    "values" => array(
        "su_avt_shon1",
        "su_avt_shon2",
        "su_avt_shon3",
        "su_avt_shon4",
        "su_avt_shon5",
        "su_avt_shon6",
        "su_avt_shon7",
        "su_avt_shon8",
        "su_avt_shon9",
        "su_avt_shon_tot",
        "su_cstr_shon1",
        "su_cstr_shon2",
        "su_cstr_shon3",
        "su_cstr_shon4",
        "su_cstr_shon5",
        "su_cstr_shon6",
        "su_cstr_shon7",
        "su_cstr_shon8",
        "su_cstr_shon9",
        "su_cstr_shon_tot",
        "su_chge_shon1",
        "su_chge_shon2",
        "su_chge_shon3",
        "su_chge_shon4",
        "su_chge_shon5",
        "su_chge_shon6",
        "su_chge_shon7",
        "su_chge_shon8",
        "su_chge_shon9",
        "su_chge_shon_tot",
        "su_demo_shon1",
        "su_demo_shon2",
        "su_demo_shon3",
        "su_demo_shon4",
        "su_demo_shon5",
        "su_demo_shon6",
        "su_demo_shon7",
        "su_demo_shon8",
        "su_demo_shon9",
        "su_demo_shon_tot",
        "su_sup_shon1",
        "su_sup_shon2",
        "su_sup_shon3",
        "su_sup_shon4",
        "su_sup_shon5",
        "su_sup_shon6",
        "su_sup_shon7",
        "su_sup_shon8",
        "su_sup_shon9",
        "su_sup_shon_tot",
        "su_tot_shon1",
        "su_tot_shon2",
        "su_tot_shon3",
        "su_tot_shon4",
        "su_tot_shon5",
        "su_tot_shon6",
        "su_tot_shon7",
        "su_tot_shon8",
        "su_tot_shon9",
        "su_tot_shon_tot",
    ),
    "column_header" => array(
        __("Destinations"),
        __("Surface existante avant travaux (A)"),
        __("Surface creee (B)"),
        __("Surface creee par changement de destination (C)"),
        __("Surface supprimee (D)"),
        __("Surface supprimee par changement de destination (E)"),
        __("Surface totale = (A) + (B) + (C) - (D) - (E)"),
    ),
    "row_header" => array(
        __("Habitation"),
        __("Hebergement hotelier"),
        __("Bureaux"),
        __("Commerce"),
        __("Artisanat"),
        __("Industrie"),
        __("Exploitation agricole ou forestiere"),
        __("Entrepot"),
        __("Service public ou d'interet collectif"),
        __("Surfaces totales (m2)"),
    ),
);

// Destination, sous-destination des constructions et tableau des surfaces
$tab_surface2["1340905"] = array(
    "values" => array(
        "su2_avt_shon1",
        "su2_avt_shon2",
        "su2_avt_shon3",
        "su2_avt_shon4",
        "su2_avt_shon5",
        "su2_avt_shon6",
        "su2_avt_shon7",
        "su2_avt_shon8",
        "su2_avt_shon9",
        "su2_avt_shon10",
        "su2_avt_shon11",
        "su2_avt_shon12",
        "su2_avt_shon13",
        "su2_avt_shon14",
        "su2_avt_shon15",
        "su2_avt_shon16",
        "su2_avt_shon17",
        "su2_avt_shon18",
        "su2_avt_shon19",
        "su2_avt_shon20",
        "su2_avt_shon_tot",
        "su2_cstr_shon1",
        "su2_cstr_shon2",
        "su2_cstr_shon3",
        "su2_cstr_shon4",
        "su2_cstr_shon5",
        "su2_cstr_shon6",
        "su2_cstr_shon7",
        "su2_cstr_shon8",
        "su2_cstr_shon9",
        "su2_cstr_shon10",
        "su2_cstr_shon11",
        "su2_cstr_shon12",
        "su2_cstr_shon13",
        "su2_cstr_shon14",
        "su2_cstr_shon15",
        "su2_cstr_shon16",
        "su2_cstr_shon17",
        "su2_cstr_shon18",
        "su2_cstr_shon19",
        "su2_cstr_shon20",
        "su2_cstr_shon_tot",
        "su2_chge_shon1",
        "su2_chge_shon2",
        "su2_chge_shon3",
        "su2_chge_shon4",
        "su2_chge_shon5",
        "su2_chge_shon6",
        "su2_chge_shon7",
        "su2_chge_shon8",
        "su2_chge_shon9",
        "su2_chge_shon10",
        "su2_chge_shon11",
        "su2_chge_shon12",
        "su2_chge_shon13",
        "su2_chge_shon14",
        "su2_chge_shon15",
        "su2_chge_shon16",
        "su2_chge_shon17",
        "su2_chge_shon18",
        "su2_chge_shon19",
        "su2_chge_shon20",
        "su2_chge_shon_tot",
        "su2_demo_shon1",
        "su2_demo_shon2",
        "su2_demo_shon3",
        "su2_demo_shon4",
        "su2_demo_shon5",
        "su2_demo_shon6",
        "su2_demo_shon7",
        "su2_demo_shon8",
        "su2_demo_shon9",
        "su2_demo_shon10",
        "su2_demo_shon11",
        "su2_demo_shon12",
        "su2_demo_shon13",
        "su2_demo_shon14",
        "su2_demo_shon15",
        "su2_demo_shon16",
        "su2_demo_shon17",
        "su2_demo_shon18",
        "su2_demo_shon19",
        "su2_demo_shon20",
        "su2_demo_shon_tot",
        "su2_sup_shon1",
        "su2_sup_shon2",
        "su2_sup_shon3",
        "su2_sup_shon4",
        "su2_sup_shon5",
        "su2_sup_shon6",
        "su2_sup_shon7",
        "su2_sup_shon8",
        "su2_sup_shon9",
        "su2_sup_shon10",
        "su2_sup_shon11",
        "su2_sup_shon12",
        "su2_sup_shon13",
        "su2_sup_shon14",
        "su2_sup_shon15",
        "su2_sup_shon16",
        "su2_sup_shon17",
        "su2_sup_shon18",
        "su2_sup_shon19",
        "su2_sup_shon20",
        "su2_sup_shon_tot",
        "su2_tot_shon1",
        "su2_tot_shon2",
        "su2_tot_shon3",
        "su2_tot_shon4",
        "su2_tot_shon5",
        "su2_tot_shon6",
        "su2_tot_shon7",
        "su2_tot_shon8",
        "su2_tot_shon9",
        "su2_tot_shon10",
        "su2_tot_shon11",
        "su2_tot_shon12",
        "su2_tot_shon13",
        "su2_tot_shon14",
        "su2_tot_shon15",
        "su2_tot_shon16",
        "su2_tot_shon17",
        "su2_tot_shon18",
        "su2_tot_shon19",
        "su2_tot_shon20",
        "su2_tot_shon_tot",
    ),
    "column_header" => array(
        __("Sous-destinations"),
        __("Surface existante avant travaux (A)"),
        __("Surface creee (B)"),
        __("Surface creee par changement de destination (C)"),
        __("Surface supprimee (D)"),
        __("Surface supprimee par changement de destination (E)"),
        __("Surface totale = (A) + (B) + (C) - (D) - (E)"),
    ),
    "row_header" => array(
        __("Exploitation agricole"),
        __("Exploitation forestière"),
        __("Logement"),
        __("Hébergement"),
        __("Artisanat et commerce de détail"),
        __("Restauration"),
        __("Commerce de gros"),
        __("Activités de services où s’effectue l’accueil d’une clientèle"),
        __("Hébergement hôtelier et touristique"),
        __("Cinéma"),
        __("Locaux et bureaux accueillant du public des administrations publiques et assimilés"),
        __("Locaux techniques et industriels des administrations publiques et assimilés"),
        __("Établissements d’enseignement, de santé et d’action sociale"),
        __("Salles d’art et de spectacles"),
        __("Équipements sportifs"),
        __("Autres équipements recevant du public"),
        __("Industrie"),
        __("Entrepôt"),
        __("Bureau"),
        __("Centre de congrès et d’exposition"),
        __("Surfaces totales (en m2)"),
    ),
);
$tab_surface2["1340910"] = array(
    "values" => array(
        "su2_avt_shon1",
        "su2_avt_shon2",
        "su2_avt_shon3",
        "su2_avt_shon4",
        "su2_avt_shon5",
        "su2_avt_shon6",
        "su2_avt_shon7",
        "su2_avt_shon8",
        "su2_avt_shon10",
        "su2_avt_shon21",
        "su2_avt_shon22",
        "su2_avt_shon11",
        "su2_avt_shon12",
        "su2_avt_shon13",
        "su2_avt_shon14",
        "su2_avt_shon15",
        "su2_avt_shon16",
        "su2_avt_shon17",
        "su2_avt_shon18",
        "su2_avt_shon19",
        "su2_avt_shon20",
        "su2_avt_shon_tot",
        "su2_cstr_shon1",
        "su2_cstr_shon2",
        "su2_cstr_shon3",
        "su2_cstr_shon4",
        "su2_cstr_shon5",
        "su2_cstr_shon6",
        "su2_cstr_shon7",
        "su2_cstr_shon8",
        "su2_cstr_shon10",
        "su2_cstr_shon21",
        "su2_cstr_shon22",
        "su2_cstr_shon11",
        "su2_cstr_shon12",
        "su2_cstr_shon13",
        "su2_cstr_shon14",
        "su2_cstr_shon15",
        "su2_cstr_shon16",
        "su2_cstr_shon17",
        "su2_cstr_shon18",
        "su2_cstr_shon19",
        "su2_cstr_shon20",
        "su2_cstr_shon_tot",
        "su2_chge_shon1",
        "su2_chge_shon2",
        "su2_chge_shon3",
        "su2_chge_shon4",
        "su2_chge_shon5",
        "su2_chge_shon6",
        "su2_chge_shon7",
        "su2_chge_shon8",
        "su2_chge_shon10",
        "su2_chge_shon21",
        "su2_chge_shon22",
        "su2_chge_shon11",
        "su2_chge_shon12",
        "su2_chge_shon13",
        "su2_chge_shon14",
        "su2_chge_shon15",
        "su2_chge_shon16",
        "su2_chge_shon17",
        "su2_chge_shon18",
        "su2_chge_shon19",
        "su2_chge_shon20",
        "su2_chge_shon_tot",
        "su2_demo_shon1",
        "su2_demo_shon2",
        "su2_demo_shon3",
        "su2_demo_shon4",
        "su2_demo_shon5",
        "su2_demo_shon6",
        "su2_demo_shon7",
        "su2_demo_shon8",
        "su2_demo_shon10",
        "su2_demo_shon21",
        "su2_demo_shon22",
        "su2_demo_shon11",
        "su2_demo_shon12",
        "su2_demo_shon13",
        "su2_demo_shon14",
        "su2_demo_shon15",
        "su2_demo_shon16",
        "su2_demo_shon17",
        "su2_demo_shon18",
        "su2_demo_shon19",
        "su2_demo_shon20",
        "su2_demo_shon_tot",
        "su2_sup_shon1",
        "su2_sup_shon2",
        "su2_sup_shon3",
        "su2_sup_shon4",
        "su2_sup_shon5",
        "su2_sup_shon6",
        "su2_sup_shon7",
        "su2_sup_shon8",
        "su2_sup_shon10",
        "su2_sup_shon21",
        "su2_sup_shon22",
        "su2_sup_shon11",
        "su2_sup_shon12",
        "su2_sup_shon13",
        "su2_sup_shon14",
        "su2_sup_shon15",
        "su2_sup_shon16",
        "su2_sup_shon17",
        "su2_sup_shon18",
        "su2_sup_shon19",
        "su2_sup_shon20",
        "su2_sup_shon_tot",
        "su2_tot_shon1",
        "su2_tot_shon2",
        "su2_tot_shon3",
        "su2_tot_shon4",
        "su2_tot_shon5",
        "su2_tot_shon6",
        "su2_tot_shon7",
        "su2_tot_shon8",
        "su2_tot_shon10",
        "su2_tot_shon21",
        "su2_tot_shon22",
        "su2_tot_shon11",
        "su2_tot_shon12",
        "su2_tot_shon13",
        "su2_tot_shon14",
        "su2_tot_shon15",
        "su2_tot_shon16",
        "su2_tot_shon17",
        "su2_tot_shon18",
        "su2_tot_shon19",
        "su2_tot_shon20",
        "su2_tot_shon_tot",
    ),
    "column_header" => array(
        __("Sous-destinations"),
        __("Surface existante avant travaux (A)"),
        __("Surface creee (B)"),
        __("Surface creee par changement de destination (C)"),
        __("Surface supprimee (D)"),
        __("Surface supprimee par changement de destination (E)"),
        __("Surface totale = (A) + (B) + (C) - (D) - (E)"),
    ),
    "row_header" => array(
        __("Exploitation agricole"),
        __("Exploitation forestière"),
        __("Logement"),
        __("Hébergement"),
        __("Artisanat et commerce de détail"),
        __("Restauration"),
        __("Commerce de gros"),
        __("Activités de services où s’effectue l’accueil d’une clientèle"),
        __("Cinéma"),
        __("Hôtels"),
        __("Autres hébergements touristiques"),
        __("Locaux et bureaux accueillant du public des administrations publiques et assimilés"),
        __("Locaux techniques et industriels des administrations publiques et assimilés"),
        __("Établissements d’enseignement, de santé et d’action sociale"),
        __("Salles d’art et de spectacles"),
        __("Équipements sportifs"),
        __("Autres équipements recevant du public"),
        __("Industrie"),
        __("Entrepôt"),
        __("Bureau"),
        __("Centre de congrès et d’exposition"),
        __("Surfaces totales (en m2)"),
    ),
);

// Locaux à usage d’habitation principale et leurs annexes
$tab_tax_su_princ["13409"] = array(
    "values" => array(
        "tax_su_princ_log_nb1",
        "tax_su_princ_log_nb2",
        "tax_su_princ_log_nb3",
        "tax_su_princ_log_nb4",
        "tax_su_princ_surf1",
        "tax_su_princ_surf2",
        "tax_su_princ_surf3",
        "tax_su_princ_surf4",
    ),
    "column_header" => array(
        "",
        __("Nombre de logement"),
        __("Surfaces creees"),
    ),
    "row_header" => array(
        __("Ne beneficiant pas de pret aide"),
        __("Beneficiant d'un PLAI ou LLTS"),
        __("Beneficiant d'autres prets aides"),
        __("Beneficiant d'un pret a taux zero plus"),
    ),
);
$tab_tax_su_princ["1340903"] = array(
    "values" => array(
        "tax_su_princ_log_nb1",
        "tax_su_princ_log_nb2",
        "tax_su_princ_log_nb4",
        "tax_su_princ_log_nb3",
        "tax_su_princ_surf1",
        "tax_su_princ_surf2",
        "tax_su_princ_surf4",
        "tax_su_princ_surf3",
        "tax_su_princ_surf_stat1",
        "tax_su_princ_surf_stat2",
        "tax_su_princ_surf_stat4",
        "tax_su_princ_surf_stat3",
    ),
    "column_header" => array(
        "",
        __("Nombre de logements crees"),
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces creees pour le stationnement clos et couvert"),
    ),
    "row_header" => array(
        __("Ne beneficiant pas de pret aide"),
        __("Beneficiant d'un PLAI ou LLTS"),
        __("Beneficiant d'un pret a taux zero plus (PTZ+)"),
        __("Beneficiant d'autres prets aides (PLUS, LES, PSLA, PLS, LLS)"),
    ),
);
$tab_tax_su_princ["1340909"] = array(
    "values" => array(
        "tax_su_princ_log_nb1",
        "tax_su_princ_log_nb2",
        "tax_su_princ_log_nb4",
        "tax_su_princ_log_nb3",
        "tax_su_princ_surf1",
        "tax_su_princ_surf2",
        "tax_su_princ_surf4",
        "tax_su_princ_surf3",
        "f1gu1_f1gu2_f1gu3",
        "f1lu1_f1lu2_f1lu3",
        "f1zu1_f1zu2_f1zu3",
        "f1pu1_f1pu2_f1pu3",
        "f1gt4_f1gt5_f1gt6",
        "f1lt4_f1lt5_f1lt6",
        "f1zt4_f1zt5_f1zt6",
        "f1pt4_f1pt5_f1pt6",
    ),
    "column_header" => array(
        "",
        __("Nombre de logements crees"),
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces créées pour le stationnement clos et couvert non situées dans la verticalité du bâti"),
        __("Surfaces créées pour le stationnement clos et couvert situées dans la verticalité du bâti"),
    ),
    "row_header" => array(
        __("Ne beneficiant pas de pret aide"),
        __("Beneficiant d'un PLAI ou LLTS"),
        __("Beneficiant d'un pret a taux zero plus (PTZ+)"),
        __("Beneficiant d'autres prets aides (PLUS, LES, PSLA, PLS, LLS)"),
    ),
);

// Locaux à usage d’hébergement et leurs annexes
$tab_tax_su_heber["13409"] = array(
    "values" => array(
        "tax_su_heber_log_nb1",
        "tax_su_heber_log_nb2",
        "tax_su_heber_log_nb3",
        "tax_su_heber_surf1",
        "tax_su_heber_surf2",
        "tax_su_heber_surf3",
    ),
    "column_header" => array(
        "",
        __("Nombre de logement"),
        __("Surfaces creees"),
    ),
    "row_header" => array(
        __("Ne beneficiant pas de pret aide"),
        __("Beneficiant d'un PLAI ou LLTS"),
        __("Beneficiant d'autres prets aides"),
    ),
);
$tab_tax_su_heber["1340903"] = array(
    "values" => array(
        "tax_su_heber_log_nb1",
        "tax_su_heber_log_nb2",
        "tax_su_heber_log_nb3",
        "tax_su_heber_surf1",
        "tax_su_heber_surf2",
        "tax_su_heber_surf3",
        "tax_su_heber_surf_stat1",
        "tax_su_heber_surf_stat2",
        "tax_su_heber_surf_stat3",
    ),
    "column_header" => array(
        "",
        __("Nombre de logements crees"),
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces creees pour le stationnement clos et couvert"),
    ),
    "row_header" => array(
        __("Ne beneficiant pas de pret aide"),
        __("Beneficiant d'un PLAI ou LLTS"),
        __("Beneficiant d'autres prets aides"),
    ),
);
$tab_tax_su_heber["1340909"] = array(
    "values" => array(
        "tax_su_heber_log_nb1",
        "tax_su_heber_log_nb2",
        "tax_su_heber_log_nb3",
        "tax_su_heber_surf1",
        "tax_su_heber_surf2",
        "tax_su_heber_surf3",
        "f1hu1_f1hu2_f1hu3",
        "f1mu1_f1mu2_f1mu3",
        "f1qu1_f1qu2_f1qu3",
        "f1ht4_f1ht5_f1ht6",
        "f1mt4_f1mt5_f1mt6",
        "f1qt4_f1qt5_f1qt6",
    ),
    "column_header" => array(
        "",
        __("Nombre de logements crees"),
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces créées pour le stationnement clos et couvert non situées dans la verticalité du bâti"),
        __("Surfaces créées pour le stationnement clos et couvert situées dans la verticalité du bâti"),
    ),
    "row_header" => array(
        __("Ne beneficiant pas de pret aide"),
        __("Beneficiant d'un PLAI ou LLTS"),
        __("Beneficiant d'autres prets aides"),
    ),
);

// Locaux à usage d’habitation secondaire et leurs annexes
$tab_tax_su_secon["13409"] = array(
    "values" => array(
        "tax_su_secon_log_nb",
        "tax_su_secon_surf",
    ),
    "column_header" => array(
        "",
        __("Nombre de logements crees"),
        __("Surfaces creees"),
    ),
    "row_header" => array(
        __("Locaux a usage d'habitation secondaire et leurs annexes"),
    ),
);
$tab_tax_su_secon["1340903"] = array(
    "values" => array(
        "tax_su_secon_log_nb",
        "tax_su_secon_surf",
        "tax_su_secon_surf_stat",
    ),
    "column_header" => array(
        "",
        __("Nombre de logements crees"),
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces creees pour le stationnement clos et couvert"),
),
"row_header" => array(
        __("Locaux a usage d'habitation secondaire et leurs annexes"),
    ),
);
$tab_tax_su_secon["1340909"] = array(
    "values" => array(
        "tax_su_secon_log_nb",
        "tax_su_secon_surf",
        "f1xu1_f1xu2_f1xu3",
        "f1xt4_f1xt5_f1xt6",
    ),
    "column_header" => array(
        "",
        __("Nombre de logements crees"),
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces créées pour le stationnement clos et couvert non situées dans la verticalité du bâti"),
        __("Surfaces créées pour le stationnement clos et couvert situées dans la verticalité du bâti"),
),
"row_header" => array(
        __("Locaux a usage d'habitation secondaire et leurs annexes"),
    ),
);

// Nombre total de logements
$tab_tax_su_tot["13409"] = array(
    "values" => array(
        "tax_su_tot_log_nb",
        "tax_su_tot_surf",
    ),
    "column_header" => array(
        "",
        __("Nombre de logement"),
        __("Surfaces"),
    ),
    "row_header" => array(
        __("Nombre total de logements"),
    ),
);
$tab_tax_su_tot["1340903"] = array(
    "values" => array(
        "tax_su_tot_log_nb",
        "tax_su_tot_surf",
        "tax_su_tot_surf_stat",
    ),
    "column_header" => array(
        "",
        __("Nombre de logements crees"),
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces creees pour le stationnement clos et couvert"),
    ),
    "row_header" => array(
        __("Nombre total de logements"),
    ),
);
$tab_tax_su_tot["1340909"] = array(
    "values" => array(
        "tax_su_tot_log_nb",
    ),
    "column_header" => array(
        "",
        __("Nombre de logements crees"),
    ),
    "row_header" => array(
        __("Nombre total de logements"),
    ),
);

// Création ou extension de locaux non destinés à l’habitation
$tab_tax_su_non_habit_surf["13409"] = array(
    "values" => array(
        "tax_su_non_habit_surf1",
        "tax_su_non_habit_surf2",
        "tax_su_non_habit_surf3",
        "tax_su_non_habit_surf4",
        "tax_su_non_habit_surf5",
        "tax_su_non_habit_surf6",
        "tax_su_non_habit_surf7",
    ),
    "column_header" => array(
        "",
        __("Surfaces creees"),
    ),
    "row_header" => array(
        __("Total des surfaces creees ou supprimees, y compris les surfaces des annexes"),
        __("Locaux industriels et leurs annexes"),
        __("Locaux artisanaux et leurs annexes"),
        __("Entrepots et hangars faisant l'objet d'une exploitation commerciale et non ouverts au public"),
        __("Parc de stationnement couverts faisant l'objet d'une exploitation commerciale"),
        __("Dans les exploitations et cooperatives agricoles : Surfaces de plancher des serres de production, des locaux destines a abriter les recoltes, heberger les
animaux, ranger et entretenir le materiel agricole, des locaux de production et de stockage des produits
a usage agricole, des locaux de transformation et de conditionnement des produits provenant de
l'exploitation
"),
        __("Dans les centres equestres :
Surfaces de plancher affectees aux seules activites equestres
"),
    ),
);
$tab_tax_su_non_habit_surf["1340903"] = array(
    "values" => array(
        "tax_su_non_habit_surf1",
        "tax_su_non_habit_surf2",
        "tax_su_non_habit_surf3",
        "tax_su_non_habit_surf4",
        "tax_su_non_habit_surf5",
        "tax_su_non_habit_surf6",
        "tax_su_non_habit_surf7",
        "tax_su_non_habit_surf_stat1",
        "tax_su_non_habit_surf_stat2",
        "tax_su_non_habit_surf_stat3",
        "tax_su_non_habit_surf_stat4",
        "tax_su_non_habit_surf_stat5",
        "tax_su_non_habit_surf_stat6",
        "tax_su_non_habit_surf_stat7",
    ),
    "column_header" => array(
        "",
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces creees pour le stationnement clos et couvert"),
    ),
    "row_header" => array(
        __("Total des surfaces creees ou supprimees, y compris les surfaces des annexes"),
        __("Locaux industriels et leurs annexes"),
        __("Locaux artisanaux et leurs annexes"),
        __("Entrepots et hangars faisant l'objet d'une exploitation commerciale et non ouverts au public"),
        __("Parc de stationnement couverts faisant l'objet d'une exploitation commerciale"),
        __("Dans les exploitations et cooperatives agricoles : Surfaces de plancher des serres de production, des locaux destines a abriter les recoltes, heberger les
animaux, ranger et entretenir le materiel agricole, des locaux de production et de stockage des produits
a usage agricole, des locaux de transformation et de conditionnement des produits provenant de
l'exploitation
"),
        __("Dans les centres equestres :
Surfaces de plancher affectees aux seules activites equestres
"),
    ),
);
$tab_tax_su_non_habit_surf["1340907"] = array(
    "values" => array(
        "tax_su_non_habit_surf1",
        "tax_su_non_habit_surf8",
        "tax_su_non_habit_surf9",
        "tax_su_non_habit_surf4",
        "tax_su_non_habit_surf5",
        "tax_su_non_habit_surf6",
        "tax_su_non_habit_surf7",
        "tax_su_non_habit_surf_stat1",
        "tax_su_non_habit_surf_stat8",
        "tax_su_non_habit_surf_stat9",
        "tax_su_non_habit_surf_stat4",
        "tax_su_non_habit_surf_stat5",
        "tax_su_non_habit_surf_stat6",
        "tax_su_non_habit_surf_stat7",
    ),
    "column_header" => array(
        "",
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces creees pour le stationnement clos et couvert"),
    ),
    "row_header" => array(
        __("Total des surfaces creees ou supprimees, y compris les surfaces des annexes"),
        __("Locaux industriels et artisanaux ainsi que leurs annexes"),
        __("Maisons de santé mentionnées à l’article L. 6323-3 du code de la santé publique"),
        __("Entrepots et hangars faisant l'objet d'une exploitation commerciale et non ouverts au public"),
        __("Parc de stationnement couverts faisant l'objet d'une exploitation commerciale"),
        __("Dans les exploitations et cooperatives agricoles : Surfaces de plancher des serres de production, des locaux destines a abriter les recoltes, heberger les animaux, ranger et entretenir le materiel agricole, des locaux de production et de stockage des produits a usage agricole, des locaux de transformation et de conditionnement des produits provenant de l'exploitation"),
        __("Dans les centres equestres : Surfaces de plancher affectees aux seules activites equestres"),
    ),
);
$tab_tax_su_non_habit_surf["1340909"] = array(
    "values" => array(
        "tax_su_non_habit_surf1",
        "tax_su_non_habit_surf8",
        "tax_su_non_habit_surf9",
        "tax_su_non_habit_surf4",
        "tax_su_non_habit_surf6",
        "tax_su_non_habit_surf7",
        "f2cu1_f2cu2_f2cu3",
        "f2bu1_f2bu2_f2bu3",
        "f2su1_f2su2_f2su3",
        "f2hu1_f2hu2_f2hu3",
        "f2eu1_f2eu2_f2eu3",
        "f2qu1_f2qu2_f2qu3",
        "f2ct4_f2ct5_f2ct6",
        "f2bt4_f2bt5_f2bt6",
        "f2st4_f2st5_f2st6",
        "f2ht4_f2ht5_f2ht6",
        "f2et4_f2et5_f2et6",
        "f2qt4_f2qt5_f2qt6",
    ),
    "column_header" => array(
        "",
        __("Surfaces creees hormis les surfaces de stationnement closes et couvertes"),
        __("Surfaces créées pour le stationnement clos et couvert non situées dans la verticalité du bâti"),
        __("Surfaces créées pour le stationnement clos et couvert situées dans la verticalité du bâti"),
    ),
    "row_header" => array(
        __("Total des surfaces creees ou supprimees, y compris les surfaces des annexes"),
        __("Locaux industriels et artisanaux ainsi que leurs annexes"),
        __("Maisons de santé mentionnées à l’article L. 6323-3 du code de la santé publique"),
        __("Entrepots et hangars faisant l'objet d'une exploitation commerciale et non ouverts au public"),
        __("Dans les exploitations et cooperatives agricoles : Surfaces de plancher des serres de production, des locaux destines a abriter les recoltes, heberger les animaux, ranger et entretenir le materiel agricole, des locaux de production et de stockage des produits a usage agricole, des locaux de transformation et de conditionnement des produits provenant de l'exploitation"),
        __("Dans les centres equestres : Surfaces de plancher affectees aux seules activites equestres"),
    ),
);

// Parcs de stationnement couverts faisant l’objet d’une exploitation commerciale
$tab_tax_su_parc_statio_expl_comm["1340903"] = array(
    "values" => array(
        "tax_su_parc_statio_expl_comm_surf",
    ),
    "column_header" => array(
        "",
        __("Surfaces creees"),
    ),
    "row_header" => array(
        __("Parcs de stationnement couverts faisant l’objet d’une exploitation commerciale"),
    ),
);

// Autres éléments soumis à la taxe d’aménagement et modifiés
$tab_tax_am["13409"] = array(
    "values" => array(
        "tax_am_statio_ext",
        "tax_sup_bass_pisc",
        "tax_empl_ten_carav_mobil_nb",
        "tax_empl_hll_nb",
        "tax_eol_haut_nb",
        "tax_pann_volt_sup",
    ),
    "column_header" => array(
        "",
        __("Cree"),
    ),
    "row_header" => array(
        __("Nombre de places de stationnement situees a l'exterieur de la construction modifie :"),
        __("Superficie du bassin de la piscine modifiee :"),
        __("Nombre d'emplacements de tentes, de caravanes et de residences mobiles de loisirs modifie :"),
        __("Nombre d'emplacements pour les habitations legeres de loisirs modifie :"),
        __("Nombre d'eoliennes dont la hauteur est superieure a 12 m modifie :"),
        __("Superficie des panneaux photovoltaiques poses au sol modifiee :"),
    ),
);

// Effectif
$tab_erp_eff["1382403"] = array(
    "values" => array(
        "erp_loc_eff1",
        "erp_loc_eff2",
        "erp_loc_eff3",
        "erp_loc_eff4",
        "erp_loc_eff5",
        "erp_loc_eff_tot",
        "erp_public_eff1",
        "erp_public_eff2",
        "erp_public_eff3",
        "erp_public_eff4",
        "erp_public_eff5",
        "erp_public_eff_tot",
        "erp_perso_eff1",
        "erp_perso_eff2",
        "erp_perso_eff3",
        "erp_perso_eff4",
        "erp_perso_eff5",
        "erp_perso_eff_tot",
        "erp_tot_eff1",
        "erp_tot_eff2",
        "erp_tot_eff3",
        "erp_tot_eff4",
        "erp_tot_eff5",
        "erp_tot_eff_tot",
    ),
    "column_header" => array(
        "",
        __("Types de locaux (local / taux d’occupation)"),
        __("Public"),
        __("Personnel"),
        __("TOTAL"),
    ),
    "row_header" => array(
        __("Sous-sol"),
        __("Rez-de-chaussee"),
        __("1er etage"),
        __("2e etage"),
        __("3e etage"),
        __("Effectif cumule"),
    ),
);

