# run tests manually in the Actions-tab of the project
name: PHP test
on:
  workflow_dispatch:
    inputs:
        DINOSAUR:
            description: 'test'
            required: false

permissions:
  contents: write
  actions: read
  checks: write
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Install Composer
              uses: php-actions/composer@v6 # or alternative dependency management
              with:
                working_dir: my_app
              
            - name: PhpUnit
              run: ls
              # uses: php-actions/phpunit@v3
              # with:
              #   configuration: "phpunit.xml.dist"