# run tests manually in the Actions-tab of the project
name: PHP test
on:
  workflow_dispatch:
    inputs:
        DINOSAUR:
            description: 'test'
            required: false

permissions:
  contents: write
  actions: read
  checks: write
jobs:
    CI:
        runs-on: ubuntu-latest
        container:
          image: php:8.2-cli
          volumes:
            - ./:/var/www/app
        steps:
            - uses: actions/checkout@v4
            - name: apt install
              run: apt-get -qq update && apt-get -qq install libpq-dev unzip libgd-dev libicu-dev curl locales -y
            - name: install composer and phpunit
              run: |
                curl https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                curl -LO https://phar.phpunit.de/phpunit-9.6.phar
                whereis phpunit-9.6.phar
            - name: move
              run: |
                cd /var/www/app
            - name: compose install
              run: |
                ls
                composer install
            - name: php unit
              run: |
                cd ../../../
                php phpunit-9.6.phar --version

            
            # - name: Install Composer
            #   uses: php-actions/composer@v6 # or alternative dependency management
            #   with:
            #     php_version: "8.2"
            #     command: update

            # # - name: test
            # #   run: |
            # #     cd my_app
            # #     php bin/console
            # #     ./vendor/bin/phpunit
            # - name: test2
            #   run : ./vendor/bin/phpunit


            # - name: PhpUnit
            #   uses: php-actions/phpunit@v3
            #   with:
            #     php_version: "8.2"
            #     # whitelist: my_app/
