# run tests manually in the Actions-tab of the project
name: Oral
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'Tag '
        # Input has to be provided for the workflow to run
        required: false

permissions:
  contents: write
  actions: read
  checks: write
jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: php:8.2-cli
      volumes:
        - ./:/var/www/app
    steps:
        - uses: actions/checkout@v4
        - name: apt install
          run: apt-get -qq update && apt-get -qq install libpq-dev unzip libgd-dev libicu-dev curl locales -y
        - name: install composer and phpunit
          run: |
            curl https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            curl -LO https://phar.phpunit.de/phpunit-9.6.phar
            whereis phpunit-9.6.phar
        - name: move
          run: |
            cd /var/www/app
        - name: compose install
          run: |
            ls
            composer install
            composer require --dev phpstan/phpstan
        - name: php unit
          run: php phpunit-9.6.phar
        - name: php stan
          run: vendor/bin/phpstan analyse src tests
        #- uses: php-actions/phpstan@v3
        #  with:
        #    path: /var/www/app
  CDelivery:
    runs-on: ubuntu-latest
    needs: [ CI ]
    steps:
      - uses: actions/checkout@v4

      - name: qemu
        uses: docker/setup-qemu-action@v3
      
      - name: docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: login docker
        uses: docker/login-action@v3
        with:
          username: giovanni2002ynov
          password: dckr_pat_jJptlvypHTAwfKu-Pr9O7DBn-Jk
                
      - name: build et push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{github.event.inputs.tag != ''}}
          tags: giovanni2002ynov/cicd:no-use
          labels: cicd

      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: Dockerfile

      - name: Release
        if: github.event.inputs.tag != ''
        id: release
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag -a ${{ github.event.inputs.tag }} -m "push cicd"
          echo "VERSION=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
      
      - name: Push Tag
        if: github.event.inputs.tag != ''
        run: git push --follow-tags
        
      - name: Push Release
        if: github.event.inputs.tag != ''
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "Dockerfile"
          tag: ${{ steps.release.outputs.VERSION }}
  CDeployment:
    runs-on: ubuntu-latest
    needs: [ CDelivery ]
    steps:
      - uses: actions/checkout@v4

      - name: Pull docker image
        run: docker pull giovanni2002ynov/cicd:no-use
      - name: Verifie l'image
        run: bash cicd/tests/verify_docker_image.sh
